### ISSUE TITLE
Can't see the response from Web-UI

### ISSUE THREAD

**Issue by lynch0227** [guardian/alerta#101]
Here is my alerta.conf:
DEBUG = True

MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DATABASE = 'monitoring'
MONGO_REPLSET = None  # 'alerta'

MONGO_USERNAME = 'alerta'
MONGO_PASSWORD = 'xxxxx'

AUTH_REQUIRED = False

CORS_ALLOW_HEADERS = ['Content-Type', 'Authorization','Access-Control-Allow-Origin']
CORS_ORIGINS = [
    'http://try.alerta.io',
    'http://explorer.alerta.io',
    'chrome-extension://jplkjnjaegjgacpfafdopnpnhmobhlaf',
    'http://localhost'
]
CORS_SUPPORTS_CREDENTIALS = AUTH_REQUIRED

PLUGINS = ['logstash']

AMQP_URL = 'redis://localhost:6379/'              # Redis

LOGSTASH_HOST = 'localhost'
LOGSTASH_PORT = 6379

When run the 'alertad' command, I can see the response is OK, and I also can see the alert records have been already restored into MongoDB.
192.168.x.x - - [08/Jul/2015 13:56:54] "GET /alerts/count?status=open HTTP/1.1" 200 -
192.168.x.x - - [08/Jul/2015 13:56:54] "GET /services?status=open HTTP/1.1" 200 -
192.168.x.x - - [08/Jul/2015 13:56:54] "GET /environments?status=open HTTP/1.1" 200 -
192.168.x.x - - [08/Jul/2015 13:56:54] "GET /alerts?status=open HTTP/1.1" 200 -

I use apache as web server. The alertad and WebUI are in the same server.
But I can't get them from WebUI. Here is the error message by chrome console.
XMLHttpRequest cannot load http://xx.xx.xx.xx:8080/alerts?status=open. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xx.xx.xx.xx.:9080' is therefore not allowed access.

How can I resolve this issue?

**Comment by satterly** [comment]
Try adding `http://xx.xx.xx.xx.:9080` to the `CORS_ORIGINS` setting and restart `alertad`.

**Comment by lynch0227** [comment]
That's work. Thanks.
And I have another question, can I remove 'CORS_ALLOW_HEADERS','CORS_ORIGINS','CORS_SUPPORTS_CREDENTIALS' from alerta.conf file?

**Comment by satterly** [comment]
Only include settings in your `alertad.conf` if they are different to the default values contained [here](https://github.com/guardian/alerta/blob/master/alerta/settings.py).
 
You will definitely need to keep your setting for `CORS_ORIGINS` which you just changed to allow the web UI to view alerts.

**Comment by lynch0227** [comment]
ok, I got it.
Thank you.
