### ISSUE TITLE
[POLICY] Alert environment must be one of Production, Development

### ISSUE THREAD

**Issue by BCWilsonDotCom** [guardian/alerta#106]
Environment name is too restrictive. Instead of only allowing Production or Development, any value should be accepted. For example, we use consul and have several environment names for different consul datacenters. So environment names may be prod-us-region-1, prod-us-region-2, dev-us-region-1, etc.

**Comment by satterly** [comment]
The [`reject`](https://github.com/guardian/alerta/blob/master/alerta/plugins/reject.py) plugin that enforces certain alert policies is just an example of what is possible and should be configured for different install environments, customised to enforce different alert policies (eg. only allow a subset of severity levels) or disabled if not required.

Configurable settings...
```
ORIGIN_BLACKLIST = [
    re.compile('foo/bar'),
    re.compile('qux/.*')
]

ALLOWED_ENVIRONMENTS = [
    'Production',
    'Development'
]
```

To disable, just override the `PLUGINS` setting in your environment-specific `alertad.conf` file to replace this:
```
PLUGINS = ['reject']
```
with this:
```
PLUGINS = []
```

**Comment by BCWilsonDotCom** [comment]
Ah gotcha. Thanks so much for the clarification.

**Comment by jfromaniello** [comment]
It will be nice to have the `ALLOWED_ENVIRONMENTS` configurable

**Comment by satterly** [comment]
Good suggestion. See fa946076b83ea50a347ea873e4b3a241d7de8c0d which is available right now as Alerta version 4.4.13.

**Comment by azavrin** [comment]
Hello, how do i set proper environment variable in kapcitor tickscript ?
I am getting this error:
ts=2018-01-20T09:15:03.399-08:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-fcbb5281-18e7-45ce-8efe-f3bbb9e7d406 err="[POLICY] Alert environment must be one of Production, Staging, Prodcan"

kapacitor config is set to "Produciton", however Alerta tickscript does not read that. I'm doing everything via chronograf

Thank you

**Comment by satterly** [comment]
Check your Kapacitor config ... if it really is "Produciton" then you've spelt it wrong. It should be "Production" to match the list of your `ALLOWED_ENVIRONMENTS`.

**Comment by azavrin** [comment]
Thank you for the response. Here is what kapacitor alerta section reads:
[alerta]
  # Configure Alerta.
  enabled = true
  # The Alerta URL.
  url = "http://aws-hub-alerta-01.myvest.com/api"
  # Default authentication token.
  #  token = "B46k%&!HRiNdc%a=oh0*P%04cIx3)d7Y"
  # Default token prefix
  # If you are on older versions of alerta you may need to change this to "Key"
  token-prefix = "Bearer"
  # Default environment.
  environment = "Production"
  # Default origin.
  origin = "kapacitor"

and here is what alerta reads:
SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'warning': 4,
    'indeterminate': 5,
    'ok': 5,
    'unknown': 9
}
PLUGINS=['reject']
ALLOWED_ENVIRONMENTS=['Production', 'Staging', 'Prodcan']

i get below error when kapacitor tries to send, if i remove 'reject', it works.

ts=2018-01-20T13:30:02.104-08:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-fcbb5281-18e7-45ce-8efe-f3bbb9e7d406 err="[POLICY] Alert environment must be one of Production, Staging, Prodcan"
