### ISSUE TITLE
allow setting of mongodb user/password via environment variables

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#108]
I don't see an easy way to use an environment variable to set the mongodb password.

**Comment by satterly** [comment]
Try setting the `MONGOLAB_URI ` or `MONGOHQ_URL ` environment variables in the MongoDB URI format described [here](https://docs.mongodb.org/v3.0/reference/connection-string/#standard-connection-string-format).

**Comment by satterly** [comment]
Following PR #109 use `MONGO_URI`.
