### ISSUE TITLE
[question] how does alerta api scale?

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#110]
Can I just add more instances of the API, talking to the same mongodb replica set, to handle more traffic?

I'm thinking of having thousands of hosts sending heartbeats.  How many heartbeats does alerta typically handle?

Thanks!

**Comment by satterly** [comment]
Run Alerta as a WSGI app using Apache or nginx on multiple servers, put them behind a load-balancer and use a MongoDB replica set and it should scale just fine.

I haven't tried sending thousands of heartbeats to Alerta but I don't see why it should be an issue. The only thing you will need to do is write a script to generate a report on heartbeat status and alert on hosts that have heartbeat failing.

**Comment by blysik** [comment]
Thanks for the answer!  

I'm seeing things working as expected with multiple front-ends.  So that's great.  

Aha.. so while Alerta can accept heartbeats, it doesn't notice if they go away?

**Comment by satterly** [comment]
Alerta is event-driven (ie. the events are alerts) so an external source is required to check to see if **no** heartbeat has been received for a heartbeat origin. To achieve this, I have modified the `alerta` command-line tool to add an argument called `--alert` to the the `heartbeats` sub-command.

Previously, the `alerta heartbeats` command would just list all the heartbeats received. Following alerta/python-alerta@10ae853b5dff666141be6291eae9c9372716c809, the command-line tool will now generate an alert if the timeout is exceeded or the heartbeat latency (ie. receive time - create time) is greater than 2000ms.

**Example**
In this example, a heartbeat has not been received within the 30 second timeout interval.
```
$ alerta heartbeats --alert
```
So, the above command will result in the following output:
```
ORIGIN                       TAGS                       CREATED              LATENCY TIMEOUT SINCE
web01                        linux, london              2015/09/03 00:22:35      25ms     30s *0:00:34
aed61d8e-ac77-4da8-8822-aafa1d3647b2 (normal -> major)
```
And the generated alert would look like this in the web console...

<img width="833" alt="screen shot 2015-09-03 at 00 38 52" src="https://cloud.githubusercontent.com/assets/615057/9647372/33dce368-51d4-11e5-8050-4bf6fee86c15.png">

All you need to do now is schedule this to run as often as you like in `cron`.

**Comment by blysik** [comment]
That's pretty awesome!

**Comment by satterly** [comment]
Thanks.
