### ISSUE TITLE
Modifying multiple alerts from the UI

### ISSUE THREAD

**Issue by BCWilsonDotCom** [guardian/alerta#114]
Just posting an enhancement request. I'd like to see a UI enhancement that allows modifying the states of multiple events. For example if a box has multiple services that alert on it, I'd like to ACK them all at once instead of clicking back and forth through the front page and the alert details page.

**Comment by satterly** [comment]
Command-click or Alt-click to select multiple alerts and bulk action buttons will appear at the bottom of the alert list web page.
