### ISSUE TITLE
[enhancements] support configurable OAUTH2 providers

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#116]
GitLab provides OAuth2 services: http://doc.gitlab.com/ce/integration/oauth_provider.html

If I have a local installation of GitLab, it would be nice to be able to point Alerta at it.  

Right now, however, Alerta hard codes the auth endpoints on a per service basis.  Could a configurable endpoint be created for OAuth2 sources like this?

**Comment by blysik** [comment]
Looks like that documentation is pretty sparse, and I see that twitter/github/google all implement OAuth2 slightly differently.

**Comment by blysik** [comment]
Looks like GitLab utilizes DoorKeeper to implement oauth2: https://github.com/doorkeeper-gem/doorkeeper

**Comment by satterly** [comment]
One solution would be to integrate GitLab with Google OAuth... https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/integration/google.md ... (as well as Alerta).

**Comment by blysik** [comment]
Yeah.  Unfortunately in my case, I integrate GitLab with the company's LDAP solution.  I guess another possibility is just adding LDAP authorization support to Alerta.  I was hoping OAuth2 -> GitLab would be easier, since you have code for that already.

These are the routes that GitLab via DoorKeeper uses:
GET       /oauth/authorize/:code
GET       /oauth/authorize
POST      /oauth/authorize
DELETE    /oauth/authorize
POST      /oauth/token
POST      /oauth/revoke
resources /oauth/applications
GET       /oauth/authorized_applications
DELETE    /oauth/authorized_applications/:id
GET       /oauth/token/info

**Comment by blysik** [comment]
Another possibile solution is honoring the X-Forwarded-User http header.  I am running the web UI behind a reverse nginx proxy, which can handle the authorization, and provide the userid via that http header.

**Comment by satterly** [comment]
If this was needed to authenticate directly to the API then using `X-Forwarded-User` would work however your requirement is authentication for the web console which requires a JWT auth token to a callback URL.

Authorization for the web console is based on the [satellizer](https://github.com/sahat/satellizer) token-based AngularJS authentication library. There is no built-in support for GitLab but you can configure any OAuth2 provider using the following configuration options:

```
// Generic OAuth 2.0
$authProvider.oauth2({
  name: null,
  url: null,
  clientId: null,
  redirectUri: null,
  authorizationEndpoint: null,
  defaultUrlParams: ['response_type', 'client_id', 'redirect_uri'],
  requiredUrlParams: null,
  optionalUrlParams: null,
  scope: null,
  scopePrefix: null,
  scopeDelimiter: null,
  state: null,
  type: null,
  popupOptions: null,
  responseType: 'code',
  responseParams: {
    code: 'code',
    clientId: 'clientId',
    redirectUri: 'redirectUri'
  }
});
```
There would also need to be a new callback URL added to the `auth.py` module with necessary OAuth2 flow.

**Comment by blysik** [comment]
Hmm.  Interesting.  My main motivator for authorization for the web console is to get access to the logged-in-only set of features.  So maybe this method may work.

**Comment by satterly** [comment]
Is this something you could have a go at? I could help if/when you get stuck. It's just that I know nothing about GitLab and unless there's a publicly available test/demo environment development would be slow as I'm unlikely to be able to find the time or resources to install GitLab locally.

FYI, the above satellizer config would need to be included in the Alerta web console [app.js file](https://github.com/alerta/angular-alerta-webui/blob/master/app/js/app.js#L91-L108) and a new Oauth2 callback URL added to the Alerta API server [auth.py file](https://github.com/guardian/alerta/blob/master/alerta/app/auth.py#L170).

**Comment by blysik** [comment]
I'll give it a go.

**Comment by blysik** [comment]
Is this the correct docs to be following?

http://requests-oauthlib.readthedocs.org/en/latest/oauth2_workflow.html

**Comment by satterly** [comment]
That's one example of an OAuth2 workflow. To get a more general idea read the RFC which describes the [implicit grant](https://tools.ietf.org/html/rfc6749#section-1.3.2) which is used by web browsers.

This stackoverflow question neatly summarises the [flow](http://stackoverflow.com/questions/25455132) and which if you look at the code in `auth.py` you'll see the same or very similar steps.

**Comment by satterly** [comment]
@blysik Any luck with this? Do you need some help?

**Comment by blysik** [comment]
I've spent some time on this, then got pulled away by work duties.  Not sure when I'll be able to revisit.

**Comment by satterly** [comment]
If I can find some time I'll take a look.

**Comment by blysik** [comment]
Here's an implementation of the gitlab oauth flow that the RocketChat people wrote: 
https://github.com/wellingtonufsc/Rocket.chat-nute/tree/2fcbdb94d2641044f1a9c6933667695cdde0ccbc/packages/rocketchat-custom-oauth

I'm trying to find something to make this easier for me.

**Comment by blysik** [comment]
I think I'm going to have to throw in the towel on this one.  My python and grasp of oauth is too poor.  I'm not making any headway here.

**Comment by satterly** [comment]
For this to work you **must** set the `GITLAB_URL` configuration variable otherwise Alerta won't know where to authenticate to.

Also, I have assumed that a Gitlab group is like a Github organisation so that you can restrict who can login to Alerta by checking if they are members of a group defined by `ALLOWED_GITLAB_GROUPS`.

An OAuth2 client ID needs to be created with a valid callback URL which points to the location of the Alerta web UI, not the Alerta API.

![screen shot 2015-10-21 at 10 31 31](https://cloud.githubusercontent.com/assets/615057/10632902/0ca066e0-77df-11e5-815d-0b54ca44fd39.png)

**Comment by satterly** [comment]
This is now available on Pypi as Alerta server [version 4.5.2](https://pypi.python.org/pypi/alerta-server/4.5.2). You will need to update to the most recent version of the web UI as well.

**Comment by satterly** [comment]
See live demo that uses [GitLab.com](https://gitlab.com/) as OAuth provider at https://alerta.herokuapp.com You will need to [sign up](https://gitlab.com/users/sign_in) to GitLab.com first.

**Comment by blysik** [comment]
Wow!  

Just wanted to provide you feedback that it works great with a private GitLab server also!  

Thanks so much for implementing this.

**Comment by qed-** [comment]
Is it possible to authenticate using an internal github server?
I can see the GITLAB_URL variable but not one for github.

**Comment by satterly** [comment]
Not at the moment but I don't see why it shouldn't be possible with a bit of work. Assuming that the OAuth flow for Github enterprise is similar to Github.com then it's just a matter of having a config variable like `GITHUB_URL` (as you point out) and pointing things at that. How urgent/important is this?

**Comment by satterly** [comment]
@qed- I've added this to the backlog.

**Comment by momania** [comment]
Can I add a +1 for adding `GITHUB_URL` ?

**Comment by satterly** [comment]
@qed- / @momania I've added support for GitHub Enterprise logins. You will need to update to Alerta server 4.8.26 and the lastest web UI.

To configure, add `GITHUB_URL` to you server config settings...

```
AUTH_REQUIRED = True
ADMIN_USERS=['satterly']
OAUTH2_CLIENT_ID = 'client-id-goes-here'
OAUTH2_CLIENT_SECRET = 'foobarbaz'

GITHUB_URL = 'https://github.example.com'
ALLOWED_GITHUB_ORGS = ['guardian']
CORS_ORIGINS=['http://alertawebui.example.com']
```
And add the `github_url` setting to the web UI `config.js`...

```
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'    : "http://alerta-api.example.com",
    'provider'    : "github", 
    'client_id'   : "client-id-goes-here",
    'github_url'  : "https://github.example.com"
  });
```

Please test and let me know if there are any issues.

**Comment by momania** [comment]
Great, thanks!
Will test asap (but that will probably be earliest next week)

**Comment by momania** [comment]
Got it setup now by building my own docker image, based on https://github.com/alerta/docker-alerta

But the callback to `/api/auth/github` gives a `502 Bad Gateway`

```
2017-02-06 09:08:53,463 DEBG 'nginx' stdout output:
2017/02/06 09:08:53 [error] 30#30: *12 upstream prematurely closed connection while reading response header from upstream, client: X.X.X.X, server: , request: "POST /api/auth/github HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "<myhost>:8181", referrer: "http://<myhost>:8181/"

2017-02-06 09:08:53,463 DEBG 'nginx' stdout output:
ip=\- [\06/Feb/2017:09:08:53 +0000] "\POST /api/auth/github HTTP/1.1" \502 \584 "\http://<myhost>:8181/" "\Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
```

From here it's all nginx black magic to me. 😢 
Any clue what might be wrong in the nginx or uwsgi setup of the docker image?

**Comment by satterly** [comment]
I just googled and found this in GitHub Enterprise 2.4.0 release notes ...

>Upcoming deprecation of authentication using GitHub OAuth
User authentication via GitHub OAuth is being deprecated and will be removed in a future feature release. It will be removed no sooner than November 2015.

https://enterprise.github.com/releases/series/2.4

What version of GitHub enterprise are you running?

**Comment by momania** [comment]
We use 2.7, and OAuth is still very much in there.

**Comment by satterly** [comment]
@momania Is this still an open issue? Can you confirm if GitHub Enterprise OAuth2 logins work?

**Comment by satterly** [comment]
Closing this issue. If still a problem please re-open.
