### ISSUE TITLE
Email Notifications?

### ISSUE THREAD

**Issue by tcsweetser** [guardian/alerta#135]
Hello Chaps,

Do you have plans for or have/seen contributions for sending email/html notifications?

T

**Comment by satterly** [comment]
Hi @tcsweetser , yes there is a contributed alert mailer. It is not fully featured but could be enhanced depending on needs. See https://github.com/alerta/alerta-contrib/tree/master/integrations/mailer

Alternatively you can use the built-in integration with PagerDuty to send emails. See http://docs.alerta.io/en/latest/integrations.html#pagerduty
