### ISSUE TITLE
Running alerta query top-like?

### ISSUE THREAD

**Issue by deeplook** [guardian/alerta#142]
Is there a way to run `alerta query` like the Unix command `top` with auto updates in the terminal?

**Comment by satterly** [comment]
Yes, the command is `alerta top` and it looks like this...

<img width="682" alt="screen shot 2016-01-20 at 00 08 31" src="https://cloud.githubusercontent.com/assets/615057/12436170/bd166674-bf0a-11e5-8c5b-72584c5629b0.png">

You can sort by 'resource' ( press `r`), 'event' ( press `e`) or 'origin' (press `o`) and then `q` to quit.

There was a bug preventing it from working after some changes to the server side of things which I've [just fixed](alerta/python-alerta/pull/21) so make sure you update to version 4.6.11 using `pip install alerta --upgrade`.

**Comment by deeplook** [comment]
Thanks! I've upgraded, but I'm not sure I observe what I'd expect. When I first run `alerta top` I see output similar to that in the Angular WebUI (although much reduced). When I add alerts they show up in the `alerta top` output, but when I delete an alert in the WebUI nothing changes in the terminal. And when I run `alerta top` a second time it shows nothing.

Apart from that it would be cool to see the some alert category colors in `alerta top` like in `alerta query`.

**Comment by satterly** [comment]
That is the current behaviour. I'll look at adding something more like an updating alert list as you describe... with colors!

**Comment by satterly** [comment]
@deeplook Please update alerta to version 4.6.12 to get the enhanced `alerta top`.

**Comment by satterly** [comment]
![screen shot 2016-01-21 at 11 36 52](https://cloud.githubusercontent.com/assets/615057/12479673/a712051a-c034-11e5-8a29-143d5901fe25.png)

**Comment by deeplook** [comment]
Brilliant, thanks!
