### ISSUE TITLE
Use alarm['AlarmName'] instead of alarm['Trigger']['MetricName'] for event in cloudwatch webhook

### ISSUE THREAD

**Issue by tdi** [guardian/alerta#149]
Motivation:
AWS MetricName (e.g. RequestCount, CPUUtilization, etc.) can be used to define many different CloudWatch Alarms. For example I want alarm when `RequestCount` is too small on ELB and when it is too high. These two alarm will have the same event name (`RequestCount`), the same resource (ELB),. 

I think using AlertName as an event is better. because it says what is the even.Plus you get to customize it in AWS Cloudwatch. 

PS: If you agree I can give PR.

**Comment by satterly** [comment]
Yes. I think you're right. A pull request for this would be appreciated. Thanks.
