### ISSUE TITLE
updating user (PUT /user/<user>) should update the whole user, not just password

### ISSUE THREAD

**Issue by tdi** [guardian/alerta#152]
Now only password is updated when you `PUT /user/<user>`. According to PUT semantics, I expected to update the whole user. There is no alternative way of updating users in alerta than that. 

I can provide a PR for this.

**Comment by satterly** [comment]
You're right, `PUT` should update all provided user attributes. PR welcome.

**Comment by tdi** [comment]
ok I will create a PR in some time.
