### ISSUE TITLE
Allow closing alerts on blackout.

### ISSUE THREAD

**Issue by tdi** [guardian/alerta#176]
An example: 
- alert X with severity critical comes,
- a blackout is set cacthing alert X,
- alert X comes with OK (but is neglected).
- blackout is off,
- alert X comes with critical, and becomes a duplicate. 

Maybe there should be a blackout (configurable via `BLACKOUT_ACCEPT=['ok', 'normal']`) that pass alerts of said severities. 

Just an idea. (We can provide a PR).

**Comment by satterly** [comment]
Yes, this is a good suggestion. A PR would be very welcome. Thanks!
