### ISSUE TITLE
Limit history

### ISSUE THREAD

**Issue by CodeTripper** [guardian/alerta#188]
Is there any way I can call the api/alerts GET method to return the alerts without history?
I understand that one can limit it in the app.config but that would become system wide. I just want it to be request specific.

**Comment by satterly** [comment]
Fixed by #192

**Comment by satterly** [comment]
This is now possible by doing something like `/alerts?fields!=history`. Available for download now as version 4.7.17.

**Comment by CodeTripper** [comment]
Thanks @satterly !! Really appreciate.
