### ISSUE TITLE
Adding LDAP authorization support to Alerta

### ISSUE THREAD

**Issue by AliGouta** [guardian/alerta#194]
Is it on the roadmap to add support to LDAP ?

**Comment by satterly** [comment]
No. The web UI uses https://github.com/sahat/satellizer for client-side authentication and that library does not support LDAP only OAuth and Basic Auth. Apparently you can get [LDAP-OAuth bridges](https://www.google.co.uk/?#q=oauth%20ldap%20bridge) that might do what you want.
