### ISSUE TITLE
alerta-housekeeping.js:  "exception: $multiply only supports numeric types, not String"

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#195]
When I run alerta-housekeeping.js, I get the error below:
```
assert: command failed: {
	"errmsg" : "exception: $multiply only supports numeric types, not String",
	"code" : 16555,
	"ok" : 0,
	"$gleStats" : {
		"lastOpTime" : Timestamp(1462910955, 2),
		"electionId" : ObjectId("571ea881985b45c7dabb06ec")
	}
}
```
I'm a mongodb newbie.  Did timeout somehow get created in mongodb as a string?  Any idea how I can recover from this?

Thanks!

**Comment by satterly** [comment]
I would just delete all the existing alerts with a string timeout...

    $ mongo
    > use monitoring
    > db.alerts.remove({timeout: {$type: "string"}})

And then update your Alerta installation to get the latest version that now prevents strings from being accepted as timeout values.

**Comment by blysik** [comment]
I'm getting this error trying to remove the existing alerts:
```
mongos> db.alerts.remove({timeout: {$type: "string"}})
WriteResult({
	"nRemoved" : 0,
	"writeError" : {
		"code" : 2,
		"errmsg" : "$type has to be a number"
	}
})
```

**Comment by satterly** [comment]
what version of mongodb is this?

**Comment by blysik** [comment]
# mongo --version
MongoDB shell version: 2.6.4

**Comment by satterly** [comment]
That version of mongodb doesn't support "aliases" for types ... 
https://docs.mongodb.com/v2.6/reference/operator/query/type/#available-types
They were introduced with version 3.2 I think ...
https://docs.mongodb.com/v3.2/reference/operator/query/type/#available-types

So try this instead... 

    $ mongo
    > use monitoring
    > db.alerts.remove({timeout: {$type: 2}})

**Comment by blysik** [comment]
That worked!  Thanks. (Now to upgrade Alerta...)

**Comment by satterly** [comment]
Great.
