### ISSUE TITLE
Unable to authenticate with private GitHub organization

### ISSUE THREAD

**Issue by hexedpackets** [guardian/alerta#197]
I'm attempting to use the GitHub OAuth provider for authentication. I need to limit this access a private organization, which Alerta doesn't seem to be able to pick up. Setting `ALLOWED_GITHUB_ORGS = ['*']` works but is obviously not desirable. I've tried setting my org both by name and ID without success, every login returns 403.

**Comment by satterly** [comment]
I've just configured the demo Alerta site on Heroku to use Github OAuth2 and set `ALLOWED_GITHUB_ORGS` to `['alerta','hiveary']` and it works for me (as I'm in the "alerta" org). Test it for yourself at https://alerta.herokuapp.com

Try setting `ALLOWED_GITHUB_ORGS` to `['hiveary']` and that should work.

**Comment by satterly** [comment]
If setting via environment variables just use coma-separated like on Heroku ...

<img width="791" alt="screen shot 2016-05-20 at 00 34 44" src="https://cloud.githubusercontent.com/assets/615057/15412806/ae08a760-1e22-11e6-8dda-c491cb58a368.png">

**Comment by hexedpackets** [comment]
Thanks for setting that up but I think I miscommunicated my issue a bit. The part that doesn't seem to work is private membership - when you're set as "private" for organizational visibility. 

With Hiveary, I'm set to "public", which is why you can see me as a member. I'm trying to setup authentication for Docurated, which is set as private and doesn't appear in my public profile.

I believe being able to read these types of memberships just requires adding the "read:org" scope to the authorize call (https://github.com/login/oauth/authorize) - although after a quick search I wasn't able to find that request in the code, just the access_token call.

**Comment by satterly** [comment]
Ok. This makes more sense. I've managed to reproduce the problem and it sounds like your suggestion about adding the `read:org` scope would fix it. I'll take a look.

![screen shot 2016-05-20 at 10 22 51](https://cloud.githubusercontent.com/assets/615057/15423325/e5573efa-1e74-11e6-83fd-89439f3a55b5.png)

**Comment by satterly** [comment]
This is fixed. You'll need to update to the latest server (v4.7.20) and web UI. Thanks for reporting this and coming up with a solution.

**Comment by hexedpackets** [comment]
Awesome, just tried out the new version and it works great. Thanks for the quick fix!
