### ISSUE TITLE
Is there some way to integrate alerta with grafana?

### ISSUE THREAD

**Issue by rydeng** [guardian/alerta#203]
is there an easy way to integrate alerta with grafna？ It is stuff like plugin used by grafana

**Comment by satterly** [comment]
There will be ... https://github.com/grafana/grafana/issues/2209

**Comment by rydeng** [comment]
thanks very much,satterly.

**Comment by satterly** [comment]
I'm happy to  leave this issue open until the grafana work is complete as a reminder.

**Comment by colomboipl** [comment]
Hello Grafana v4.0 is Out!
I want to test the Alert feature. Configure a Grafana Notification Webhook to send the alerta web ui.
Can you help me .

**Comment by msupino** [comment]
adding this to views.py in app/wesocket

@app.route('/webhooks/grafana', methods=['OPTIONS', 'POST'])
@cross_origin()
@auth_required
def grafana():

    hook_started = webhook_timer.start_timer()
    alerts = parse_grafana(request.data)

    LOG.warning(alerts)

    for incomingAlert in alerts:

        LOG.warning(incomingAlert)
        if g.get('customer', None):
            incomingAlert.customer = g.get('customer')

        add_remote_ip(request, incomingAlert)

        try:
            alert = process_alert(incomingAlert)
        except RejectException as e:
            webhook_timer.stop_timer(hook_started)
            return jsonify(status="error", message=str(e)), 403
        except Exception as e:
            webhook_timer.stop_timer(hook_started)
            return jsonify(status="error", message=str(e)), 500

        webhook_timer.stop_timer(hook_started)

    if alert:
        body = alert.get_body()
        body['href'] = absolute_url('/alert/' + alert.id)
        return jsonify(status="ok", id=alert.id, alert=body), 201, {'Location': body['href']}
    else:
        return jsonify(status="error", message="insert or update of grafana check failed"), 500

def parse_grafana(check):
    check = json.loads(check)
    evalMatches = check['evalMatches']
    timeout = 60

    alerts = []

    for item in check['evalMatches']:
        LOG.warning(item['metric'])
        alerts.append(Alert(
            status='open',
            resource=item['metric'],
            event=check['state'],
            environment='Production',
            severity='critical',
            service=[check['ruleName']],
            text="Value:" + str(item['value']),
            origin='Grafana',
            event_type='Grafana_event',
            raw_data=item['value'],
            timeout=timeout,
            value='Error',
            group='group'
        ))

    return alerts

and adding this to grafana should work
http://localhost:8080/webhooks/grafana?api-key=<key> 
method=POST

**Comment by colomboipl** [comment]
Tested but not working!

**Comment by msupino** [comment]
works here.. anything in the logs regarding the POST or other exceptions ?

**Comment by colomboipl** [comment]
does the function "def parse_grafana(check):" be first than the other one like the others webhooks

**Comment by msupino** [comment]
Makes no difference..


--

Marco.

**Comment by colomboipl** [comment]
ok, i dont have api key neither login on alerta side. i think that will be easier to implement.

**Comment by colomboipl** [comment]
This is my error from alerta side:

t=2016-12-02T19:32:58+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=webhook id=0 isDefault=false
t=2016-12-02T19:32:58+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
t=2016-12-02T19:32:58+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Webhook response status 500 Internal Server Error" webhook=Alerta_io

**Comment by colomboipl** [comment]
The problem is in the add_remote_ip function .

**Comment by msupino** [comment]
Can u share the alerta log in debug mode? The log I saw is from grafana

**Comment by colomboipl** [comment]
I put it . Iḿ using the docker image from docker hub and I see that the alerta has an update that included the function add_remote_ip. Iḿ using now the new alerta but I have a problem with connection to the mongo

**Comment by colomboipl** [comment]
OK Now I cant put all running with yours version of the views.py. But this error occurs 

=2016-12-02T23:19:03+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=webhook id=0 isDefault=false
t=2016-12-02T23:19:03+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
t=2016-12-02T23:19:03+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Webhook response status 405 METHOD NOT ALLOWED" webhook=Alerta_io

**Comment by satterly** [comment]
Grafana webhook integration is available from Alerta server version 4.8.17.

**Comment by colomboipl** [comment]
Thanks

A Sáb, 10 de dez de 2016, 22:22, Nick Satterly <notifications@github.com>
escreveu:
