### ISSUE TITLE
Close the blackout

### ISSUE THREAD

**Issue by freeseacher** [guardian/alerta#215]
Is there a way to close blackout ?  
i want to create such workflow
0. start an ansible deploy job
1. create an alert about that deploy.
2. do deploy procedures, they will not do anything harmful, so i do not need a blackout there.
3. open a blackout for service restart. i am using supervisord with serialrestart command. so it can lasts loooong time. and generate lots of alerts about down/up.
4. close the blackout on ansible job finish. so if i got restart after this point it will be a matter of problem. 
5. close an alert about deployment

Currently i am using timed blackout, but sometimes i got restart of service some time after supervisord thinks task goes to running state. (various timeouts, network, disks and so on)

**Comment by satterly** [comment]
There is no support for deleting a current, active blackout period using the `alerta` command-line tool (you can "purge" old ones though) however you could delete an active one by using the API directly like this ...

```
$ curl -X DELETE http://alerta-api.herokuapp.com/blackout/5f61efd0-171b-4483-be30-8161ac716735 -H 'Authorization: Key 74tqZG8Zkfo29_k5Q7YOsXtvl7PVzTSPF-Sp7ibX'
```
You need a read-write API key and need to know the blackout period id which you can get from when the blackout period was created or by listing all the existing blackout periods.

See http://docs.alerta.io/en/latest/api/reference.html#blackout-periods for more info

**Comment by satterly** [comment]
I've been thinking about this a bit more and wonder if the ability to match on a blackout rule by tag is useful ...

>Tags can also be used to define a blackout rule which should allow a lot of flexibility because tags can be added at source, using the alerta CLI, or using a plug-in. Note that one or more tags can be required to match an alert for the suppression to apply.

Can you write a plugin that intercepts alerts, queries ansible and adds a "blackout" tag if the ansible deploy is still running?
