### ISSUE TITLE
Alert from heartbeats

### ISSUE THREAD

**Issue by freeseacher** [guardian/alerta#216]
Hi, as noticed in doc there are are ways to create alert from lost heartbeat. 
can you provide some example of how it can be done?

**Comment by satterly** [comment]
Send heartbeats using the `alerta` command-line tool ...

```
$ alerta heartbeat --help
usage: alerta [OPTIONS] heartbeat [-T TAG] [-O ORIGIN] [--timeout TIMEOUT]

optional arguments:
  -h, --help            show this help message and exit
  -T TAG, --tag TAG     List of tags eg. "London", "os:linux", "AWS/EC2".
  -O ORIGIN, --origin ORIGIN
                        Origin of heartbeat. Usually in form of "app/host"
  --timeout TIMEOUT     Timeout in seconds before a heartbeat will be
                        considered stale
```

Use `timeout` setting to adjust how long a heartbeat should be missing for before alerting.

Alert on heartbeats by running...

    $ alerta heartbeats --alert

**Example**

```
$ alerta heartbeats --alert
ORIGIN                       TAGS                       CREATED              LATENCY TIMEOUT SINCE             STATUS
alerta/macbookpro.home                                  2016/06/11 22:06:43     80ms    300s 0:08:22           stale
dd8f8974-def8-482c-9693-840a210b7e70 (normal -> major)
```
<img width="1186" alt="screen shot 2016-06-11 at 22 16 55" src="https://cloud.githubusercontent.com/assets/615057/15987506/3e1104d6-3022-11e6-8777-146c76a744ed.png">

So you can simply add this script to crontab on your alerta server...

    * * * * * alerta heartbeats --alert
