### ISSUE TITLE
Multiple ACK & close

### ISSUE THREAD

**Issue by kavyakul** [guardian/alerta#221]
Is there a feature or a plan to have a feature for multiple acknowledgment in a go from gui, using checkbox maybe?Right now what I find is we have to open every alert & acknowledge or close it.

**Comment by satterly** [comment]
This is already supported by holding down the cmd button ( ⌘ on mac) or alt key (windows) and then clicking multiple alerts with the mouse. See http://docs.alerta.io/en/latest/webui.html#view-recent-alerts
