### ISSUE TITLE
How to obtain API key after installing alerta?

### ISSUE THREAD

**Issue by minhdanh** [guardian/alerta#222]
I happen to reinstall alerta today (using my ansible playbooks). There's something looks like missing in the document is that I could not find a way to create an API key (the one used in the cli config so that the cli could query the server). I tried the followings:

- Run command to create an API key:
```
alerta key --no-customer --user kapacitor
2016-06-15 11:49:17,736 - alerta.shell - ERROR - Missing authorization API Key or Bearer Token
```
- I set AUTH_REQUIRED to False, restart alerta server and try again:
```
alerta key --no-customer --user kapacitor
2016-06-15 11:48:31,558 - alerta.shell - ERROR - Must supply API Key or Bearer Token when creating new API key
```

This seems like a chicken and egg problem: to get an API key for the cli config we have to create it first. But to create a key we have to use an existing API key.

So how should I obtain the API key after installing alerta server?

**Comment by satterly** [comment]
Use the web GUI to create the first key.

**Comment by minhdanh** [comment]
Actually that feature seems not work for me. I enter an application name and hit "Create new API Key", then I see the same screen. No API Key is created.

**Comment by satterly** [comment]
Are you running the latest version of the web UI? see #204

**Comment by minhdanh** [comment]
Yes, I updated the web UI to the latest version. Still the same.

**Comment by satterly** [comment]
And the latest version of alerta server? Have you enable authentication? ie. set `AUTH_REQUIRED` to `True`?

**Comment by minhdanh** [comment]
Using alerta 4.7.26. Almost the latest : )

**Comment by PMDubuc** [comment]
Is that web UI the only way to create the first user and API key?  That makes automating the installation more difficult if you want to set up users and keys that way.

**Comment by satterly** [comment]
@PMDubuc No, not any more. You can use the `alertad` command-line tool to create users and API keys...
```
$ alertad --help

Usage: alertad [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  key     Create an admin API key
  keys    List admin API keys
  routes  Show the routes for the app.
  run     Runs a development server.
  shell   Runs a shell in the app context.
  user    Create admin user
  users   List admin users
```

It's used extensively by the docker container to create Admin users and API keys. See https://github.com/alerta/docker-alerta/blob/master/docker-entrypoint.sh

Let me know if you need any more info.
