### ISSUE TITLE
Alerts to telegram

### ISSUE THREAD

**Issue by freeseacher** [guardian/alerta#226]
Hi can you please make alerts to telegram plugin ? 
We have some kind of public infrastructure so alerts to slack seems overkill. 
Recently it was added to kapacitor https://github.com/influxdata/kapacitor/pull/680
and that is very cool!

**Comment by msupino** [comment]
try this
----------------------------------------
import os
import json
import requests

from alerta.app import app
from alerta.plugins import PluginBase

import telebot

LOG = app.logger

TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN') or app.config['TELEGRAM_TOKEN']
TELEGRAM_CHATID = os.environ.get('TELEGRAM_CHATID') or app.config['TELEGRAM_CHATID']
ALERTA_UI_URL = os.environ.get('ALERTA_UI_URL', 'http://try.alerta.io')

bot = telebot.TeleBot(TELEGRAM_TOKEN)

class TelegramIntegration(PluginBase):

    def pre_receive(self, alert):
        return alert

    def post_receive(self, alert):

        if alert.repeat:
            return

        summary = "*[%s] %s %s - _%s on %s_* <%s/#/alert/%s|%s>" % (
            alert.status.capitalize(), alert.environment, alert.severity.capitalize(), alert.event, alert.resource, ALERTA_UI_URL,
            alert.id, alert.get_id(short=True)
        )
        text = "<%s/#/alert/%s|%s> %s - %s" % (ALERTA_UI_URL, alert.get_id(), alert.get_id(short=True), alert.event, alert.text)

        LOG.debug('Telegram text: %s', summary)

        try:
            r = bot.send_message(TELEGRAM_CHATID, text)
        except Exception as e:
            raise RuntimeError("Telegram connection error: %s", e)

        LOG.debug('Telegram response: %s', r)

    def status_change(self, alert, status, text):
        return

**Comment by satterly** [comment]
Thanks! I'll add this to the [contrib](https://github.com/alerta/alerta-contrib) repo

**Comment by msupino** [comment]
and a setup.py for it

#!/usr/bin/env python

import setuptools

version = '0.0.1'

setuptools.setup(
    name="alerta-telegram",
    version=version,
    description='Alerta plugin for Telegram',
    url='https://github.com/alerta/alerta-contrib',
    license='Apache License 2.0',
    author='Marco Supino',
    author_email='marco@supino.org',
    py_modules=['telegram'],
    install_requires=[
        'pyTelegramBotAPI',
        'alerta-server'
    ],
    include_package_data=True,
    zip_safe=False,
    entry_points={
        'alerta.plugins': [
            'telegram = telegram:TelegramIntegration'
        ]
    }
)

**Comment by freeseacher** [comment]
some additions 
https://gist.github.com/freeseacher/d8fa1683831dff31e882a59d78b71947

**Comment by satterly** [comment]
Thanks, both. I've added a Telegram plugin [here](alerta/alerta-contrib#106).
