### ISSUE TITLE
Duplicates and repeats

### ISSUE THREAD

**Issue by mikesand** [guardian/alerta#227]
Hi,

I found an issue where if you correlate two or more alerts and send the same two alerts multiple times Alerta does not see them as repeats. Once I then send only one alert of the two or more correlated alerts, repeat is true and duplicates are made. I'm not sure where in the code to start looking for the cause.

Regards,

Mike

**Comment by satterly** [comment]
Can you give me examples of what you mean? Ideally example `alerta send` commands that I can run in order to reproduce the behaviour. Thanks.

**Comment by satterly** [comment]
Looks good to me...
```
$ alerta send -S Svc -E Development -r r1 -e event1 -C event2 -C event3 -s warning -t 1
f651cf7c-6cf2-4a53-83d7-dc6b0f3430f9 (unknown -> warning)
$ alerta send -S Svc -E Development -r r1 -e event1 -C event2 -C event3 -s warning -t 2
f651cf7c-6cf2-4a53-83d7-dc6b0f3430f9 (1 duplicates)
$ alerta send -S Svc -E Development -r r1 -e event2 -C event1 -C event3 -s warning -t 3
f651cf7c-6cf2-4a53-83d7-dc6b0f3430f9 (warning -> warning)
$ alerta send -S Svc -E Development -r r1 -e event2 -C event1 -C event3 -s warning -t 4
f651cf7c-6cf2-4a53-83d7-dc6b0f3430f9 (1 duplicates)
```

**Comment by satterly** [comment]
If this isn't what you are seeing or you can provide a list of `alerta send` commands that reproduce your problem please add them below and reopen this issue.
