### ISSUE TITLE
Blackout period created with environment of None

### ISSUE THREAD

**Issue by satterly** [guardian/alerta#233]
Running `alerta blackout` without any options creates a blackout period with an environment of `None`...
```
(alerta)macbookpro:~ nsatterl$ alerta --profile development blackout
1af87346-27e2-447e-9c96-a5cc006ec952
(alerta)macbookpro:~ nsatterl$ alerta --profile development blackouts
ID       CUSTOMER         ENVIRONMENT      SERVICE          RESOURCE         EVENT            GROUP            TAGS                     STATUS   START               DURATION
1af87346 *                None             *                *                *                *                *                        active   2016/08/02 00:36:40 3600s
2ab35f9b *                Production       StatusCake       *                *                *                *                        active   2016/08/02 00:36:56 3600s

**Comment by wangbodong** [comment]
192.168.10.1 - - [02/Dec/2016 10:52:42] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:42] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:43] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:43] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/top10/flapping?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/top10/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/count?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /environments?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/top10/count?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/top10/flapping?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /environments?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/top10/count?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/count?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/top10/flapping?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/top10/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/top10/flapping?status=open&status=unknown HTTP/1.1" 200 -
