### ISSUE TITLE
the meaning of count in top10 page

### ISSUE THREAD

**Issue by annProg** [guardian/alerta#236]
Hi

My event name like  HTTP_CODE:$url， so the value of count in top10 page is always equal to 1.

I want to know the status change times of an event, but not the event count(event is always uniq in my environment), like 'NUMBER OF STATUS CHANGES' in zabbix triggers top 100.  Is there any way to do it?

Thanks

**Comment by satterly** [comment]
Ok, this is more like a top ten "flapping" count than a top ten "offenders" count. I don't think that is  possible with the existing `/top10` endpoint.

A top 10 flapping query response would be skewed by the limit placed on the number of history log entries for an alert but it would probably still be useful. Would that meet your requirements?

**Comment by satterly** [comment]
<img width="960" alt="screen shot 2016-08-18 at 21 42 54" src="https://cloud.githubusercontent.com/assets/615057/17790050/c6db187a-658c-11e6-8ec8-da445e3d8a12.png">

**Comment by satterly** [comment]
Update to latest versions of both server and web UI to get this new feature.

**Comment by annProg** [comment]
Thanks a million! I have upgraded to the latest version
