### ISSUE TITLE
Max retries Exceeded

### ISSUE THREAD

**Issue by mikesand** [guardian/alerta#240]
Anyone ever seen this? I get it from command line and from my application.

2016-08-18 23:53:47,682 - alerta.shell - ERROR - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /management/status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe33135c4d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by satterly** [comment]
You will see this error if the alerta server is not running. Try `curl http://localhost:8080` and let me know what you get.

**Comment by mikesand** [comment]
The server had massive issues unrelated to Alerta and had to be rebuilt. I'm sure that was the issue.

**Comment by mikesand** [comment]
Ok, this is back and very strange. I get HTTPConnectionPool(host='40.x.x.x, port=8080): Max retries exceeded with url. 

Alerta is running and it only happens sporadically. 
Almost no load on the server. 
A reboot didn't help. 
Health Status is OK. 
<900 alerts in the DB. 
I tried pinging from the server and didn't see any timeouts during the issue.

Anything else I can try?

**Comment by satterly** [comment]
Can you tell me how Alerta API is configured to run? As a Wsgi app, using apache or nginx? Or some other way?

> Flask’s built-in server is not suitable for production as it doesn’t scale well and by default serves only one request at a time

see http://flask.pocoo.org/docs/0.12/deploying/#deployment-options

**Comment by mikesand** [comment]
As an Wsgi app.

**Comment by mikesand** [comment]
Like this... Should I adjust the threads?

Listen 8080
<VirtualHost *:8080>
  ServerName localhost
  WSGIDaemonProcess alerta processes=5 threads=5
  WSGIProcessGroup alerta
  WSGIApplicationGroup %{GLOBAL}
  WSGIScriptAlias / /var/www/api.wsgi
  WSGIPassAuthorization On
  <Directory /opt/alerta>
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
  </Directory>
</VirtualHost>
<VirtualHost *:80>
  ProxyPass /api http://localhost:8080
  ProxyPassReverse /api http://localhost:8080
  DocumentRoot /var/www/alerta/app
  <Directory /var/www/alerta/app>
    Require all granted
  </Directory>
</VirtualHost>

**Comment by satterly** [comment]
Not sure. Can we move this to https://gitter.im/alerta/chat ?

**Comment by mikesand** [comment]
Thanks for you help earlier. This was tied back to an issue with our Azure cluster not Alerta (we were losing packets and confirmed this with a tcpdump). That said, we are probably going to route the alerta api traffic through a proxy we use for all other communication to handle retries. We use the requests library differently so adding it to api.py would be a larger project but if we have time we will look at changing that and submitting it.

**Comment by LaurianoElmiroDuarte** [comment]
@satterly
I have the same problem, I installed my alert, through the docke, what can this problem be?

**Comment by satterly** [comment]
You are probably using the wrong API endpoint path. The API path for the docker container has`/api` on the end.
