### ISSUE TITLE
Notify different group or even protocol on diffrent alert

### ISSUE THREAD

**Issue by freeseacher** [guardian/alerta#241]
Hi, 
currently alerta looks like "notification aggregator" for me, but i really cant see any possibility to send info about alarms to different people or even protocols, or at least different chat groups...  
I have to notify my manager by email, and other team prefer slack or telegram. some of them have to be notified about only specific types of alerts. I already ave them in db but how can i send them ? 

Alerta have really lots of filed that describes the alert but where is some kind of "alert router" ? 
Am i ready documentation wrong?

**Comment by freeseacher** [comment]
any ideas ?

**Comment by satterly** [comment]
There is an outstanding pull request to do just what you ask for (see #220). I was waiting for some feedback before I merged it. 

This should enable you to route alerts to different notification plugins based on alert attributes.

You could try this branch and give me feedback or if you can wait until next week I'll meege this and make it a new release available for download.

**Comment by freeseacher** [comment]
Nick, thats cool! 
and of cause i want to take part in tests. but in #220 i see only mentions about routing plugins, but no plugins :( Are they missing from pr?

**Comment by satterly** [comment]
The plugins themselves do not change. Everything should work as before unless you add a `routing.py` file which has a “rules” method. you get access to the list of available plugins and the current alert and need to return the list of plugins you want the alert to be sent to.

**Comment by satterly** [comment]
Example routing file https://github.com/guardian/alerta/blob/7fd5f97f2ded6272df69253f419da09abe6ad769/contrib/routing/routing.py

**Comment by qwding** [comment]
Waiting for the notify plugin.
