### ISSUE TITLE
Only publish major and critical alerts to SNS

### ISSUE THREAD

**Issue by squeral** [guardian/alerta#242]
Is there a way to prevent publishing all alerts to SNS?

Could we just add an If statement here: https://github.com/guardian/alerta/blob/master/alerta/plugins/sns.py#L52 ?

**Comment by satterly** [comment]
You could do that or you could wait for me to merge and deploy pull request #220 which will give you more control over when plugins are triggered. I'll merge when I get back from leave early next week.

**Comment by squeral** [comment]
That PR looks great!
I'll wait for it, thank you!

**Comment by satterly** [comment]
@squeral The new "plugin routing" feature has been merged and is available in Alerta server version 4.8 onwards.
