### ISSUE TITLE
notification after X alerts

### ISSUE THREAD

**Issue by msupino** [guardian/alerta#250]
Is it possible to add to an alert when it should send notification ? lets say i want alerta to only notify  me of issues  when duplicate > 2 , and not immediately

it should still show on the dashboard,  but not send alerts (email, slack etc)

**Comment by JacksonHill** [comment]
I think you can achieve that, by slightly modifying plugin code, at the end of post_receive function. In case of slack just add a condition to check duplicateCount before requests.post - [line 77 in slack plugin](https://github.com/alerta/alerta-contrib/blob/master/plugins/slack/slack.py#L77) at this moment

**Comment by satterly** [comment]
Yes, that is one way to do it. The other way is to make use of the new "plugin routing" feature available from Alerta version 4.8 onwards which would look something like this ...

```python
def rules(alert, plugins):

    if alert.duplicateCount > 2:
        return [plugins['slack']]
    else:
        return []
```

See https://github.com/guardian/alerta/tree/master/contrib/routing for more info.

**Comment by msupino** [comment]
this will require a change to all alert methods, if i have mail and slack, i need to add both, tomorrow ill add a third one.. i want something more generic

**Comment by satterly** [comment]
@msupino The method suggested by @JacksonHill would require a change to all alert plugins as you say. However, the new "plugin routing" feature was specifically added so that you no longer needed to do this. You only need to create one "routing.py" file with a rules method (show above) and then you return a list of plugins that should be triggered for that alert. Does that make sense?

**Comment by msupino** [comment]
this is less generic than i wanted.. but ill give it a try

thanks.

**Comment by satterly** [comment]
@msupino I'm not sure how much more generic it could be. But let me know if it doesn't meet your requirements and we'll see what we can do. Feedback always welcome.

**Comment by msupino** [comment]
where are these rules defined ? in the conf ? its not clear

**Comment by msupino** [comment]
i dont think this will work.. seems like alert are only sent on first API call, returning a plugin list to an alert wont trigger it being sent again
