### ISSUE TITLE
housekeeping script

### ISSUE THREAD

**Issue by msupino** [guardian/alerta#251]
Seems like housekeeping doesnt handle services in ACK status, although they might have exipred, is this on purpose ? any logic behind it ? i dont see a reason to keep acknowledged services who's timeout have expired

**Comment by satterly** [comment]
Doesn't it then make sense to just expire all alerts that aren't already in `expired` status? ie. if it already expires `open` and you want it to expire `ack` as well then we might as well expire `closed` too. Alerts in `closed` status would be deleted with two hours anyway so it would only actually change anything if the `timeout` was less than two hours.

**Comment by satterly** [comment]
Just tested PR #252 and the HK script now correctly expires **all** non-expired alerts if the timeout value has been exceeded.

**Comment by msupino** [comment]
Seems to handle the issue, thanks
