### ISSUE TITLE
Setting up development environment with uWSGI, Nginx, and alerta sources

### ISSUE THREAD

**Issue by JacksonHill** [guardian/alerta#256]
Hi Nick,

below you can find an instruction, how to run alerta from sources, using uWSGI and Nginx, so you can add it into the docs.
1. Clone the repository
2. Prepare installation directory - /opt/alerta for API, /opt/alerta-web for Angular UI
3. Setup virtualenv: `mkdir /opt/alerta/venv && virtualenv /opt/alerta/venv`
4. install uwsgi - `pip install uwsgi`
5. install alerta - `./venv/bin/python setup.py develop`  - note **develop** instead of **install**
6. uwsgi setup file:

```
[uwsgi]
base = /opt/alerta
master = true
app = alerta.app
module = %(app)
home = /opt/alerta/venv
pythonpath = %(base)
http = 127.0.0.1:5005
chmod-socket=664
callable = app
logto = /opt/alerta/alerta/log/%n.log
```
1. nginx setup file(correct the indents):

```
upstream alerta_api {
       server 127.0.0.1:5005;
}
server {
   listen      8000;
    server_name localhost;
    charset     utf-8;
    client_max_body_size 75M;

    location / { try_files $uri @alerta; }
    location @alerta {
        index index.html;
        root /opt/alerta-web/app;
    }
    location /api/ {
        include uwsgi_params;
        proxy_pass http://alerta_api/;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
1. Ubuntu start script /etc/init/alerta.conf

```
description "alerta uWSGI start script"
start on runlevel [2345]
stop on runlevel [06]
respawn

env UWSGI=/opt/alerta/venv/bin/uwsgi
env LOGFILE=/opt/alerta/alerta/log/emperor.log

exec $UWSGI --master --emperor /opt/alerta/alerta/run/vassals --die-on-term --uid alerta --gid alerta --logto $LOGFILE
```
1. Activate start script:  `ln -s /etc/init/alerta.conf /etc/init.d/alerta && chmod +x /etc/init.d/alerta`
2. Create missing directories:
   `mkdir -p /opt/alerta/alerta/run/vassals` - for uWSGI Emperor vassals
3. Activate uwsgi script: `ln -s <uwsgi_file_location> /opt/alerta/alerta/run/vassals`
4. Start services - `service nginx start && service alerta start`
5. Navigate to http://hostname:8000/ - angular ui, http://hostname:8000/api - API

Regards
Jacek

**Comment by JacksonHill** [comment]
ugh... editor messed up the numbers

**Comment by satterly** [comment]
Awesome. Thanks!

**Comment by satterly** [comment]
Used this as the basis for the first step-by-step tutorial on the docs website. See http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html
