### ISSUE TITLE
Deploy to heroku and config variables

### ISSUE THREAD

**Issue by riccardomc** [guardian/alerta#261]
Deployment to heroku is currently not working because alertad expects `MONGOLAB_URI` to be defined while the referenced add-on (mongolab) sets `MONGODB_URI`. This causes the worker spawned by gunicorn to time out.

**Comment by satterly** [comment]
@riccardomc Hi, can you join [gitter](https://gitter.im/alerta/chat)? I'd like to talk to you about this issue.

**Comment by riccardomc** [comment]
I can confirm that PR https://github.com/guardian/alerta/pull/262 fixes the issue. I deployed alerta successfully using the [deploy to heroku button](https://github.com/alerta/heroku-api-alerta).

**Comment by satterly** [comment]
Thanks for working out the fix for this.
