### ISSUE TITLE
ACK'd alert set to open next time the alert is received

### ISSUE THREAD

**Issue by pfarmer** [guardian/alerta#263]
When an alert is ACK'd, and new duplicate alert is received, the alert switches from ACK to Open, not sure if this is intended or not, but I would have thought it should stay ACK'd, but have text, value etc.. updated?

To add some context, I have alerts pushing into alertad every 5 minutes (because alerts are cheap).

**Comment by satterly** [comment]
It should only reopen if the severity of the new alert is higher than the currently Ack'ed alert. See [state-based browser](http://docs.alerta.io/en/latest/server.html#state-based-browser) in the docs. I've just tried to recreate the issue and I can't ...

step 1 send and alert, ack it, send a duplicate

```sh
alerta send -E Production -S Test -r node1 -e BadDisk -s warning
fe26a33c-0cab-476c-8b42-05a5ba8c44b5 (unknown -> warning)
# ack alert in console
alerta send -E Production -S Test -r node1 -e BadDisk -s warning
fe26a33c-0cab-476c-8b42-05a5ba8c44b5 (1 duplicates)
# => open or ack?
```
step 2 confirm current status is "ack"
```
alerta query --filter event=BadDisk --details
fe26a33c|2016/09/29 17:16:12|warning|    1|-|Production|Test      |node1             |Misc        |BadDisk         |n/a
    status     | ack
```
step 3 send same alert but with higher severity
```sh
alerta --profile heroku send -E Production -S Test -r node1 -e BadDisk -s minor
fe26a33c-0cab-476c-8b42-05a5ba8c44b5 (warning -> minor)
```
step 4 confirm status is now "open"
```sh
alerta --profile heroku query --filter event=BadDisk --details
fe26a33c|2016/09/29 17:20:22|minor|    0|-|Production|Test      |node1             |Misc        |BadDisk         |n/a
    status     | open
```

**Comment by satterly** [comment]
There is a test scenario that checks for something similar ... https://github.com/guardian/alerta/blob/master/tests/test_alerts.py#L221

**Comment by pfarmer** [comment]
Did a test, here's the history:

  "history": [
    {
      "event": "RAMUtilHigh",
      "id": "7da4d92a-ff84-44bd-a022-e7bb412c8dac",
      "severity": "major",
      "text": "",
      "type": "external",
      "updateTime": "2016-09-27T15:31:20.671Z",
      "value": "87.87%"
    },
    {
      "event": "RAMUtilHigh",
      "id": "7da4d92a-ff84-44bd-a022-e7bb412c8dac",
      "status": "ack",
      "text": "status change via console by Peter Farmer",
      "type": "external",
      "updateTime": "2016-09-29T16:43:47.147Z"
    },
    {
      "event": "RAMUtilHigh",
      "id": "130085a8-d389-4c0b-8738-bae6dfc814c7",
      "status": "open",
      "text": "duplicate alert status change",
      "type": "auto",
      "updateTime": "2016-09-29T16:51:22.699Z"
    }
  ],


Severity didn't change, I'll check the version (a recent checkout from github I think) and do some more testing....

**Comment by satterly** [comment]
Oh. Are you setting the status of the alert to "open" when you submit it?

**Comment by pfarmer** [comment]
That will be the problem, thanks!
