### ISSUE TITLE
Problem with oembed

### ISSUE THREAD

**Issue by JacksonHill** [guardian/alerta#268]
Oembed isn't loading anymore - there is only loading screen. I have narrowed down the problem to exception: 

` File "/opt/alerta/alerta/app/utils.py", line 42, in decorated
    data = str(func(*args, **kwargs).data)
AttributeError: 'tuple' object has no attribute 'data'
`
which point's to JSONP decorator.

I think it may be something with nginx-uwsgi configuration, because it works properly, when API is launched by flask development server.

I have checked incoming headers and args (log) in both configurations and they are the same:

./alertad:
arguments: 
`ImmutableMultiDict([('callback', u'jQuery213033999841793487584_1477465316947'), ('_', u'1477465316948'), ('maxwidth', u'200'), ('title', u'JIRA'), ('url', u'http://xxx.westeurope.cloudapp.azure.com:8080/alerts/count?service=www.jira.com&status=open'), ('api-key', u'-xwVGk2D2J0bvZUayUy0ZzItXy9PNcGG6O3xta5b'), ('maxheight', u'200')])
`

headers:
`Referer: http://xxx.westeurope.cloudapp.azure.com:8000/monitor/
Content-Length:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Connection: keep-alive
Host: xxx.westeurope.cloudapp.azure.com:8080
Cache-Control: max-age=0
Accept: */*
Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Content-Type:
Accept-Encoding: gzip, deflate, sdch`

nginx-uwsgi:
arguments:
`ImmutableMultiDict([('callback', u'jQuery21305508772435219305_1477465091426'), ('_', u'1477465091427'), ('maxwidth', u'200'), ('title', u'JIRA'), ('url', u'http://xxx.westeurope.cloudapp.azure.com:8080/alerts/count?service=www.jira.com&status=open'), ('api-key', u'-xwVGk2D2J0bvZUayUy0ZzItXy9PNcGG6O3xta5b'), ('maxheight', u'200')])`

headers: 
`Referer: http://xxx.westeurope.cloudapp.azure.com:8000/monitor/
Content-Length:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Connection: keep-alive
Host: xxx.westeurope.cloudapp.azure.com:8080
Accept: */*
Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Content-Type:
Accept-Encoding: gzip, deflate, sdch`

**Comment by satterly** [comment]
I've refactored the oembed endpoint and testing shows it to work with uWsgi now.
