### ISSUE TITLE
integration with prtg

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#274]
do you think its an option?
https://kb.paessler.com/en/topic/373-what-placeholders-can-i-use-with-prtg
https://www.paessler.com/manuals/prtg/notifications_settings#http

thanks

**Comment by satterly** [comment]
Yes, it should work. Use the `POST /alert` endpoint ([more info](http://alerta.readthedocs.io/en/latest/api/reference.html?highlight=post#send-an-alert)) using those place holders to add values to the appropriate attributes.

To get an idea of what the POST data should look like you can experiment with this online [explorer](http://explorer.alerta.io/#/send).
