### ISSUE TITLE
apache log error , alerta doesnt show anything

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#279]
[Wed Nov 09 07:15:43.905230 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602] mod_wsgi (pid=17362): Target WSGI script '/var/www/api.wsgi' cannot be loaded as Python module.
[Wed Nov 09 07:15:43.905269 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602] mod_wsgi (pid=17362): Exception occurred processing WSGI script '/var/www/api.wsgi'.
[Wed Nov 09 07:15:43.905297 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602] Traceback (most recent call last):
[Wed Nov 09 07:15:43.905323 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/var/www/api.wsgi", line 4, in <module>
[Wed Nov 09 07:15:43.905366 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     from alerta.app import app as application
[Wed Nov 09 07:15:43.905389 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/__init__.py", line 96, in <module>
[Wed Nov 09 07:15:43.905415 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     db = Mongo()
[Wed Nov 09 07:15:43.905433 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database.py", line 30, in __init__
[Wed Nov 09 07:15:43.905455 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     self.connect()
[Wed Nov 09 07:15:43.905474 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database.py", line 91, in connect
[Wed Nov 09 07:15:43.905493 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     self._create_indexes()
[Wed Nov 09 07:15:43.905505 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database.py", line 95, in _create_indexes
[Wed Nov 09 07:15:43.905522 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     self._db.alerts.create_index([('environment', ASCENDING), ('resource', ASCENDING), ('event', ASCENDING)], unique=True)
[Wed Nov 09 07:15:43.905541 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/collection.py", line 1387, in create_index
[Wed Nov 09 07:15:43.905560 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     self.__create_index(keys, kwargs)
[Wed Nov 09 07:15:43.905572 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/collection.py", line 1298, in __create_index
[Wed Nov 09 07:15:43.905589 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     sock_info, cmd, read_preference=ReadPreference.PRIMARY)
[Wed Nov 09 07:15:43.905607 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/collection.py", line 208, in _command
[Wed Nov 09 07:15:43.905623 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     read_concern=read_concern)
[Wed Nov 09 07:15:43.905642 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/pool.py", line 239, in command
[Wed Nov 09 07:15:43.905660 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     read_concern)
[Wed Nov 09 07:15:43.905672 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/network.py", line 102, in command
[Wed Nov 09 07:15:43.905689 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     helpers._check_command_response(response_doc, None, allowable_errors)
[Wed Nov 09 07:15:43.905707 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/helpers.py", line 205, in _check_command_response
[Wed Nov 09 07:15:43.905744 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602]     raise OperationFailure(msg % errmsg, code, response)
[Wed Nov 09 07:15:43.905770 2016] [wsgi:error] [pid 17362:tid 139909674944256] [remote ::1:54602] OperationFailure: exception: attempt to use unsupported textIndexVersion 3; versions supported: 2, 1

**Comment by satterly** [comment]
I suspect you're using an old version of MongoDB. Try upgrading to at least MongoDB version 3.2.

**Comment by yosefy** [comment]
thanks upgrading solved the problem :)
