### ISSUE TITLE
too heavy colors

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#283]
![image](https://cloud.githubusercontent.com/assets/12940013/20269652/c5fcacee-aa8c-11e6-93b7-89402fa0ff43.png)

may be lighter (not such a strong colors may improve the ux)
or at least make the text bold

as out support has a tv with alerts, its hard to see from far like that

**Comment by satterly** [comment]
You can set the colors to anything you want. See http://alerta.readthedocs.io/en/latest/webui.html?highlight=colors#configuration
