### ISSUE TITLE
Difference between Receive time & last Receive time

### ISSUE THREAD

**Issue by kavyakul** [guardian/alerta#285]
What is the Difference between Receive time & last Receive time

**Comment by satterly** [comment]
The lastReceiveTime is always the latest time an alert was received by the server. If the alert is the first, the receiveTime and lastReceiveTime will be the same. If it is a duplicate the receiveTime will be the time it was first received and the lastReceiveTime the most recent time it was received. See http://docs.alerta.io/en/latest/api/alert.html#attributes-added-when-processing-alerts

**Comment by satterly** [comment]
If I was doing this again I might have called lastReceiveTime a more obvious name like lastModified or updateTime instead.
