### ISSUE TITLE
How to forward only some critical alerts from Nagios to Pagerduty

### ISSUE THREAD

**Issue by matdevdug** [guardian/alerta#286]
We're looking at Alerta (big fan) but have run into a problem. Because we're forwarding events from Nagios to Pagerduty, they show up as critical but they don't all page/notify. I'm wondering if there is a way to pass a critical alert to Alerta that doesn't trigger a notification flow with the existing Pagerduty integration. Thanks for your time.

**Comment by satterly** [comment]
Hi, can I clarify a few things?

Is the situation at present that Nagios sends notifications directly to PagerDuty? And do only some of the critical alerts you get in Nagios trigger PagerDuty notifications? That is...

**Current?**
Nagios => PagerDuty

Would you like Alerta to receive Nagios alerts and for Alerta to trigger notifications to PagerDuty? And if so, do you want control over which alerts from Nagios that are sent to Alerta actually trigger notifications with PagerDuty? That is...

**Future?**
Nagios => Alerta => PD integration => PagerDuty

**Comment by satterly** [comment]
With the limited information I have so far I can only suggest you use a "routing rule" to dynamically determine which alerts should be notified based on severity or any other alert attribute. See https://github.com/guardian/alerta/tree/master/contrib/routing
