### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by pommi** [guardian/alerta#290]
Here @mendix we've started to use/test alerta a couple of months ago together with InfluxDB Kapacitor. It works pretty nice. Now we want to take it to a more serious level and ideally we want to host alerta next to the rest of our infra in AWS using an AWS service (RDS) to host the database instead of MongoDB on some EC2 instance.

We've been investigating if it's possible to swap MongoDB for PostgreSQL (Amazon RDS). Looking at the alerta code that means we have to write a replacement for (or next to) https://github.com/guardian/alerta/blob/master/alerta/app/database.py, which seems doable.

- What are your thoughts about this?
- Have there been initiatives to add this already?
- Are you interested in this addition?
- Do you have any suggestions before we start building it?
- Is there a chance it will be merged when it's properly implemented?

**Comment by satterly** [comment]
You're correct in assuming everything you'd need to modify should be in `database.py`. And yes, if you wrote it, and it passed all the tests, and we had a straightforward way to select between different database engines I'd be happy to merge it. 

My feeling though is that there are some mongo-specific data structures and queries in there that are going to be tricky to do in Postgres. I'm happy to be proved wrong though.

Let me know if you need any more info.

**Comment by satterly** [comment]
PS. I looked at swapping out mongo for elasticsearch at one stage but decided it wasn't worth the effort.

**Comment by satterly** [comment]
Following #293 it is now possible to set the config option `DATABASE_BACKEND` to select between different database technologies. Only "mongo" is currently supported, obviously. However, it means to add support for Postgres create a `postgres.py` file in the `database` package directory and implement the list of methods. Then set `DATABASE_BACKEND='postgres'` in your local config file to use Postgres instead of MongoDB.

**Comment by satterly** [comment]
I'm going to close this issue as there's nothing outstanding from my side. If you need further help feel free to add to this issue or create a new one, or alternatively join https://gitter.im/alerta/chat.

**Comment by pommi** [comment]
Thanks for your preparations! I will create a pull request once I've something that is production ready.
