### ISSUE TITLE
Flapping start and Flapping stop alerts

### ISSUE THREAD

**Issue by msupino** [guardian/alerta#295]
Is there a way to detect a service is flapping , and notify its flapping once, instead of recovery,failure,recovery,failure over a period of time ?

similar to Nagios flapping detection (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html)

**Comment by satterly** [comment]
Take a look at #296 and let me know what you think.

**Comment by msupino** [comment]
Thanks, but i am not sure how to make use of this, where should that python code ?

**Comment by satterly** [comment]
That is an example plugin. I should have mentioned that. See this repo for a bunch of other example plugins... https://github.com/alerta/alerta-contrib/tree/master/plugins

**Comment by satterly** [comment]
Let me know if you need any more help with this. I'll close this issue but feel free to add comments to it or open a new one, or alternatively join https://gitter.im/alerta/chat.
