### ISSUE TITLE
I can't login with my account ,Why ? 

### ISSUE THREAD

**Issue by wangbodong** [guardian/alerta#299]
192.168.10.1 - - [02/Dec/2016 10:52:43] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:43] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/top10/flapping?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:44] "GET /alerts/top10/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/count?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /environments?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/top10/count?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:57] "GET /alerts/top10/flapping?status=open&status=ack&status=assign HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /environments?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/top10/count?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/count?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:52:59] "GET /alerts/top10/flapping?status=closed&status=expired HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/top10/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 10:53:01] "GET /alerts/top10/flapping?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 11:33:27] "OPTIONS /auth/login HTTP/1.1" 200 -
192.168.10.1 - - [02/Dec/2016 11:33:28] "OPTIONS /auth/login HTTP/1.1" 200 -

**Comment by satterly** [comment]
Did you recently upgrade?

**Comment by wangbodong** [comment]
yes, but I still can't login

**Comment by satterly** [comment]
Check your mongodb settings. The setting changed to `MONGO_URI` recently..

**Comment by wangbodong** [comment]
I don't understand how to set the MONGO_URI. Can you give me a deploy documentation of the alerta master step-by-step .Thank you very much .

**Comment by satterly** [comment]
http://docs.alerta.io/en/latest/configuration.html#mongodb-settings

log in to https://gitter.im/alerta/chat and i'll walk you thru it.

**Comment by wangbodong** [comment]
I do it as you say ,but I still have some  bad thing 
192.168.10.1 - - [05/Dec/2016 12:04:09] "GET /config.js HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:09] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:11] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:11] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:11] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:11] "GET /alerts?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:13] "GET / HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:14] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:14] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:14] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:14] "GET /alerts?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:17] "GET /services?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:17] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:17] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:17] "GET /alerts/top10/count?status=open&status=unknown HTTP/1.1" 200 -
192.168.10.1 - - [05/Dec/2016 12:04:17] "GET /alerts/top10/flapping?status=open&status=unknown HTTP/1.1" 200 -






[root@ceph1 /]# cat /etc/alertad.conf
SECRET_KEY = 'lvpHc)CGB0TFrovo8jduwDFwSvX)j2X!'

AUTH_REQUIRED = False

PLUGINS = ['reject']
ALLOWED_ENVIRONMENTS = ['Production', 'Development']  # reject alerts without allowed environments
MONGO_URI = 'mongodb://localhost:27017/monitoring'
MONGO_DATABASE = 'monitoring'

I still can't login

**Comment by satterly** [comment]
You don't even have authentication enabled so the issue has nothing to do with logins. See above ...
```
AUTH_REQUIRED = False
```

I suspect it is to do with CORS... http://alerta.readthedocs.io/en/latest/faq.html#why-can-t-i-see-any-alerts-in-the-web-browser

Do you see any errors in the Javascript console of your browser?

**Comment by wangbodong** [comment]
Thanks for your kind help,I really don't know how to set (alertad.conf and config.js). Now  I can up alerta-server ,but  at the alerta-client point ,I have seen nothing. How to set Web UI and make the alerts show out on the Web.
Thank you so much for me .

**Comment by satterly** [comment]
Please join https://gitter.im/alerta/chat if you want me to help you troubleshoot this.
