### ISSUE TITLE
adding another field to main screen

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#306]
i have instances reporting from different regions on AWS
need to put the region label on main screen
(from prometheus)

is it possible?

thanks

**Comment by satterly** [comment]
It's not currently a configuration option. You could fork the web UI repo and add the column yourself. This is a feature on the road map for the next version of the web UI. It is a long way off though.

**Comment by yosefy** [comment]
i’ll wait :)
thanks

**Comment by satterly** [comment]
@yosefy This has been implemented. See https://github.com/alerta/alerta/pull/707
