### ISSUE TITLE
insights from snmp integration

### ISSUE THREAD

**Issue by msupinodn** [guardian/alerta#314]
1. trap handler needs full path (/usr/local/bin/alerta-snmptrap)
2. snmptrapd needs to be loaded with "-m ALL", and MIB package needs to be installed, even for example to be parsed correctly

**Comment by satterly** [comment]
Thanks. I'll update the README.

**Comment by satterly** [comment]
Wow. I wish I'd updated the README earlier. See #358 for whole sorry story.
