### ISSUE TITLE
having few prometheuses can't silence alerts from alerta (only on one of them)

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#327]
may be it is possible to make it somehow

thanks

**Comment by satterly** [comment]
If the alert `origin` included the Alertmanager URL then this could be used in the `status_change()` of the prometheus plugin to dynamically determine which Alertmanager the alert came from and where to silence it.

At the moment ``origin`` is populated with ``job`` info but this can be changed. See https://github.com/guardian/alerta/blob/master/alerta/app/webhooks/views.py#L351

**Comment by satterly** [comment]
@yosefy I've worked out that the webhook payload that Prometheus sends to Alerta already includes the "externalUrl" of the sending alertmanager ...

```
{
    "alerts": [
      {
        "annotations": {
          "description": "node:9100 of job node-exporter is under high load.",
          "summary": "Instance node:9100 under high load"
        },
        "endsAt": "0001-01-01T00:00:00Z",
        "generatorURL": "http://a1dd5d00316f:9090/graph?g0.expr=node_load1+%3E+0.5&g0.tab=0",
        "labels": {
          "PROMETHEUS_URL": "http://10.1.11.1:8990/api/v1",
          "alertname": "high_load",
          "environment": "Production",
          "instance": "node:9100",
          "job": "node-exporter",
          "service": "Prometheus"
        },
        "startsAt": "2017-01-03T00:49:07.805Z",
        "status": "firing"
      }
    ],
    "commonAnnotations": {
      "description": "node:9100 of job node-exporter is under high load.",
      "summary": "Instance node:9100 under high load"
    },
    "commonLabels": {
      "alertname": "high_load",
      "environment": "Production",
      "instance": "node:9100",
      "job": "node-exporter",
      "service": "Prometheus"
    },
    "externalURL": "http://9c1307aabc93:9093",
    "groupKey": 822007289565397000,
    "groupLabels": {
      "alertname": "high_load"
    },
    "receiver": "alerta",
    "status": "firing",
    "version": "3"
  }
```
I've added it as an attribute to alerts originating from prometheus and so the prometheus "silencer" plugin to check for this when it needs to hit the alertmanager API.

**Comment by satterly** [comment]
@yosefy Update your alerta server to the latest version to get the "externalUrl" added as an attribute to Prometheus alerts. Also update to the latest version of the prometheus plugin which will use the "externalUrl" attribute value if it is available in an alert. Please test and let me know if you have any issues. Thanks.

**Comment by yosefy** [comment]
i need to checkout some brunch for prometheus plugin change?

**Comment by satterly** [comment]
No. The change is here ...
https://github.com/alerta/alerta-contrib/blob/master/plugins/prometheus/alerta_prometheus.py#L56

You will need to "unset" the `ALERTMANAGER_API_URL ` variable so that it uses the value for `externalUrl`.

**Comment by yosefy** [comment]
i don't see it set anywhere
what is the exact place to unset it?

thanks

**Comment by satterly** [comment]
Can we do this on gitter? https://gitter.im/alerta/chat
