### ISSUE TITLE
can't create new user account with web UI

### ISSUE THREAD

**Issue by lionelmazeyrat** [guardian/alerta#335]
Message : Error! Sign up failed when trying to create a new user account.
version 4.8 or 4.8.26
I try to achieve a basic user authentification with web UI

**Comment by satterly** [comment]
What's the error in the web browser JavaScript console?

**Comment by lionelmazeyrat** [comment]
:8000/#/signup:1 XMLHttpRequest cannot load http://127.0.0.1:8080/auth/signup. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.
controllers.js:921 Object {data: null, status: -1, config: Object, statusText: ""}
angular.js:13708 TypeError: Cannot read property 'message' of null
    at controllers.js:924
    at angular.js:16170
    at m.$eval (angular.js:17444)
    at m.$digest (angular.js:17257)
    at m.$apply (angular.js:17552)
    at l (angular.js:11697)
    at K (angular.js:11903)
    at XMLHttpRequest.e (angular.js:11846)
(anonymous) @ angular.js:13708
(anonymous) @ angular.js:10347
(anonymous) @ angular.js:16178
$eval @ angular.js:17444
$digest @ angular.js:17257
$apply @ angular.js:17552
l @ angular.js:11697
K @ angular.js:11903
e @ angular.js:11846

**Comment by satterly** [comment]
This is a [CORS issue](http://alerta.readthedocs.io/en/latest/faq.html#why-can-t-i-see-any-alerts-in-the-web-browser) not specific to creating a user. I would guess nothing else is working either.

Adding the following to your `alertad.conf` server configuration file should fix the problem for you...

```
CORS_ORIGINS = [
    'http://127.0.0.1:8000'
]
```

**Comment by lionelmazeyrat** [comment]
Thanks, this solved my issue !
