### ISSUE TITLE
feature request : color line according to status and severity combination

### ISSUE THREAD

**Issue by lionelmazeyrat** [guardian/alerta#336]
in web UI, will be a great setting to color a line according to (status + severity) combination

**Comment by satterly** [comment]
Interesting suggestion. There would potentially be 54 different colour combinations though as there a [9 severity levels](https://github.com/guardian/alerta/blob/master/alerta/settings.py#L54) and [6 different statuses](https://github.com/guardian/alerta/blob/master/alerta/app/status_code.py#L23).

**Comment by lionelmazeyrat** [comment]
Yes, alarm management in scada software are often colored according this combination ! or a color and blink combination

**Comment by satterly** [comment]
Added to the backlog. Probably for the next major version of the web UI (which might be some time away yet).
