### ISSUE TITLE
feature request : full alarm history between a start and an end date

### ISSUE THREAD

**Issue by lionelmazeyrat** [guardian/alerta#337]
A new menu "history" (like recent, top 10 , watch) to consult a full alarm history between a start and  #an end date !

**Comment by satterly** [comment]
Is this typical of a Scada alarm management system? To show alerts at each status change in a chronological list?

Alerta does display individual alert history at the bottom of the alert details page. I assume this doesn't meet your specific requirements.

<img width="1301" alt="screen shot 2017-01-21 at 19 41 34" src="https://cloud.githubusercontent.com/assets/615057/22177238/c5f25d06-e011-11e6-914c-e60c8c84d5a8.png">

**Comment by lionelmazeyrat** [comment]
Yes, the existing feature is great, history for one alarm where are focused
on. The feature to add would be an history of all king of alarms occured
between a start and an end date. This is the way scada software enable to
query and display alarms.

Regards,
Lionel

**Comment by satterly** [comment]
I like this idea. I'll add it to the backlog for the next major version of Alerta server and web UI.
