### ISSUE TITLE
alerts with status "warning" immediately get closed

### ISSUE THREAD

**Issue by yosefy** [guardian/alerta#338]
and doc is not clear how to change this behaving

**Comment by satterly** [comment]
This sounds odd. Do you have "[housekeeping](http://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#step-1-housekeeping)" configured to expire timed-out alerts?

**Comment by yosefy** [comment]
yes i have default housekeepingAlerts.js
running every minute

**Comment by satterly** [comment]
Can you check the `timeout` value for these warning alerts?

```
$ alerta query --filter severity=warning --details | grep timeout
```

**Comment by yosefy** [comment]
empty
it also happen without sending any status

if alert is critical it work ok

thanks

BTW
doc says that event and resource is enough but also you have to send
service and environment
which is not a problem just to let know

**Comment by satterly** [comment]
Sorry, try this ...
```
alerta query --filter severity=warning status=~"closed|expired" --details | grep timeout
```

**Comment by yosefy** [comment]
hi Nick i really don't know why ,but it is working now. i will update.
pls lets close the issue
thanks
PS why don't you create slack channel for such things?

**Comment by satterly** [comment]
There is. We use gitter. I assumed you knew.

[![Gitter chat](https://badges.gitter.im/alerta/chat.png)](https://gitter.im/alerta/chat)
