### ISSUE TITLE
alert filter fromtime erro

### ISSUE THREAD

**Issue by msupinodn** [guardian/alerta#341]
api request 

http://api.alerta.io/alerts?limit=10&api-key=demo-key&from-date=2017-02-03T22:00

fails

with error

{
  "message": "time data '2017-02-03T22:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'", 
  "status": "error"
}

**Comment by satterly** [comment]
':00.000Z' is missing. This works... 
http://api.alerta.io/alerts?limit=10&api-key=demo-key&from-date=2017-02-03T22:00:00.000Z

**Comment by msupinodn** [comment]
thanks, this works, the sample in the demo explorer doesnt work.

**Comment by satterly** [comment]
Thanks for letting me know. I'll fix.

**Comment by satterly** [comment]
Fixed alerta/angular-alerta-explorer@486fee6a4a9a7565e8c2749787b94dc792b19539
