### ISSUE TITLE
Issue with Service Name

### ISSUE THREAD

**Issue by mikesand** [guardian/alerta#343]
Unless I missed it (totally possible) the alert Service name doesn't get updated if it changes. Is there any way to force this behavior so that an alert created earlier can use the latest service name if it changes?

**Comment by satterly** [comment]
When a duplicate is received, only a limited subset of attributes are updated ... 
```
        Update alert value, text and rawData, increment duplicate count and set repeat=True, and
        keep track of last receive id and time but don't append to history unless status changes.
```
How often does the `service` name change?

**Comment by mikesand** [comment]
We use the Service name to denote the location where our probes are so they can be changed frequently. It's ok, I'll simply run a delete of the alerts when the name is changed as part of the process.

**Comment by net592** [comment]
I have the same problem..
I need to update the Service Name every time

**Comment by net592** [comment]
Thank you very much
