### ISSUE TITLE
Feature: support for Keycloak

### ISSUE THREAD

**Issue by m4ce** [guardian/alerta#347]
It would be handy if Alerta had support for a generic OpenID/OAuth authenticator such as Keycloak. This would also solve the problem of connecting Alerta to LDAP since Keycloak can take care of that.

**Comment by m4ce** [comment]
I have actually written it myself and now testing it. Once done, I will open a PR.

**Comment by satterly** [comment]
Available now as Alerta server version 4.9.0.
