### ISSUE TITLE
Alerta WebUI is not fetching result in Chrome, but is working perfectly in IE

### ISSUE THREAD

**Issue by csomnath** [guardian/alerta#350]
I am running alerta as a container.
It works perfectly in IE but does not fetch result in Chrome.
Any idea where do I need to check since I am very much new to alerta.

**Comment by satterly** [comment]
Hi. What versions​ of Alerta, chrome and IE are you using?

**Comment by csomnath** [comment]
Alerta 4.8.19
Chrome version : Version 57.0.2987.110 (64-bit)
IE version : 11

**Comment by satterly** [comment]
Are there any errors in the [chrome javascript console](https://developers.google.com/web/tools/chrome-devtools/console/)?

**Comment by csomnath** [comment]
in the console, I see the following : 
:8001/#/alerts?status=open&status=unknown:1 XMLHttpRequest cannot load http://localhost:8082/environments?status=open&status=unknown. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8001' is therefore not allowed access.

**Comment by satterly** [comment]
Add `http://localhost:8001` (where your Alerta web UI is hosted) to your API server `CORS_ORIGINS` setting.

**Comment by farahshabnam** [comment]
Hi,

I updated the cors-settings in "README.md" as :

    CORS_ORIGINS = [
        'http://try.alerta.io',
        'http://explorer.alerta.io',
        'http://localhost:8001',
    ]
Have i changed the correct file? As i am still not able to see chrome fetching the results.

SCEERNSHOT:  https://cloud.githubusercontent.com/assets/27487369/25419190/b3ce2702-2a6e-11e7-89b8-3524f788f06b.png

**Comment by csomnath** [comment]
the container that we are using does not have alerta.conf file. Is there any other alternate file where we can update the CORS settings ? 
We have config.js file and web.js file

**Comment by satterly** [comment]
either set the `CORS_ORIGINS` environment variable ...

```
$ docker run --name alerta-web -e CORS_ORIGINS=http://localhost:8001 \
  -p 80 alerta/alerta-web
```
... or create an `alertad.conf` file ...

```
$ docker run -v $PWD/config/alertad.conf:/etc/alertad.conf \
  -v $PWD/config/config.js:/app/config.js \
  -p 80 alerta/alerta-web
```

if you're still having trouble join the [gitter chat room](https://gitter.im/alerta/chat)

**Comment by csomnath** [comment]
OK I am creating a alertad.conf file , the content of the file is just the CORS settings like below 
CORS_ORIGINS = [
    'http://localhost:8001'
]
is this fine ? and then  I will be running the container as below 
docker run -v $PWD/config/alertad.conf:/etc/alertad.conf \
  -v $PWD/config/config.js:/app/config.js \
  -p 80 <container_name>

Is the above method correct ?

**Comment by satterly** [comment]
looks ok to me. does it work?

**Comment by satterly** [comment]
Closing. Please re-open if you are still having problems.
