### ISSUE TITLE
Routing plugin documentation

### ISSUE THREAD

**Issue by thehilll** [guardian/alerta#352]
Apologies if I am misunderstanding something, but is the documentation on a routing plugin that intends to enable multiple plugins correct?

I am trying to match on a condition and when met return a list of multiple plugins to execute.  All other cases should execute all enabled plugins.  Looking at the docs for executing multiple plugins it shows:

`return [plugins['slack', 'pagerduty']]`

and so I used (with a mix of built in and our my own plugins):

`return [plugins['reject', 'influxdb', 'add_url', 'slack_detail']]`

However, with verbose logging on I see this when any alert encounters this path:

`alerta.plugins[25018]: WARNING - Plug-in routing rules failed: ('reject', 'influxdb', 'add_url', 'slack_detail') [in /opt/alerta/lib/python2.7/site-packages/alerta/plugins/__init__.py:73`

And then all plugins execute (the default).  Looking at the code noted above:

```
try:
    if self.plugins and self.rules:
        return self.rules(alert, self.plugins)
except Exception as e:
    LOG.warning("Plugin routing rules failed: %s" % str(e))

return self.plugins.values()
```

It seems to be an error in that try block, and in fact this gives the behavior I am looking for:

`return [plugins['reject'], plugins['influxdb'], plugins['add_url'], plugins['slack_detail']]`

So should the last example [here](http://alerta.readthedocs.io/en/latest/gettingstarted/tutorial-3-plugins.html?highlight=routing#step-3-route-alerts-to-plugins) in fact have the line:

`return [plugins['slack'], plugins['pagerduty']]`

Thanks.

**Comment by satterly** [comment]
Yes, you are right. Thanks for letting me know. I hope this didn't cause you too much trouble. Fixed 4e1377d9398fbb71f947529581d75294224b2c2e
