### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by arulvelu21** [guardian/alerta#356]
I installed alerta in Aws ubuntu 14.04 . I have configured alertmanager to send alerts to alerta. When i query the Api i am getting the JSON response without any hassle. But when i tried to see in UI i get the following error "No 'Access-Control-Allow-Origin' header is present on the requested resource." Can u please suggest what is the issues with this Cors origin .

**Comment by satterly** [comment]
http://docs.alerta.io/en/latest/faq.html#why-can-t-i-see-any-alerts-in-the-web-browser
