### ISSUE TITLE
Timeout ignored after an expired alert

### ISSUE THREAD

**Issue by aqmdla2002-2** [guardian/alerta#357]
Environment:
Ubuntu 16.04.2 LTS
Alerta 4.9.3

Steps to reproduce:
1) Send an alert
alerta send -r user01 -e fail -s major -E Development -S Security -t 'user01 login failed.' --timeout 20
> 50919a41-a18b-4b8f-bebb-4b6284daf7f4 (indeterminate -> major)
Go to Alert Web UI and after a short time you could see that the alert is expired
2) Wait until alert is expired
3) Send a new alert but with a new timeout
alerta send -r user01 -e fail -s major -E Development -S Security -t 'user01 login failed.' --timeout 60
> 50919a41-a18b-4b8f-bebb-4b6284daf7f4 (1 duplicates)
After step 3, go to Alert Web UI and see the details of the new alert and you could see that timeout is the original (20 seconds)

Same issue if you create an alert without timeout (default timeout is 1d) and you acknowledge and create a new alert with timeout (timeout = 86400).

Regards

**Comment by satterly** [comment]
"Processing alert and heartbeat timeouts requires a scheduled cron job." See this tutorial for how to make timeouts work ... http://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#tutorial-2

**Comment by aqmdla2002-2** [comment]
The scheduled cron is setup and working (see step 2)

**Comment by satterly** [comment]
Ok. I didn't realise you were following the tutorial already. Can we continue this on [gitter](https://gitter.im/alerta/chat)?

**Comment by satterly** [comment]
Hi @aqmdla2002-2 , is this still an issue?

**Comment by satterly** [comment]
Closing this for now. Please reopen if this is still a problem. Thanks.
