### ISSUE TITLE
snmptrap's are not sent to alerta

### ISSUE THREAD

**Issue by johnyhema** [guardian/alerta#358]

**Comment by johnyhema** [comment]
can we add right click tool for alerta events in alerta ??
i.e., if we right click the event in alerta we need to get some options like delete, ack, update.....

**Comment by satterly** [comment]
Setting up `snmptrap` is difficult so I'm not surprised you are having problems. I just tried to install it from scratch on an Ubuntu server and after much messing about I got it working. Here are some of the things I came across...
  - `alerta-snmptrap` not in the path
  - SNMP MIBs not downloaded and in the right directory
  - `snmptrapd` not configured to start
  - `snmptrapd` not configured to use downloaded SNMP MIB files

After getting all the above right I managed to receive correctly translated SNMP traps in Alerta ...

<img width="1268" alt="screen shot 2017-07-01 at 18 55 36" src="https://user-images.githubusercontent.com/615057/27764342-06ca8c3a-5e8f-11e7-8644-a81d6436956c.png">

I have updated the SNMP trap [README](https://github.com/alerta/alerta-contrib/blob/master/integrations/snmptrap/README.md) with everything that I discovered so hopefully you'll have more success if you review that again carefully. Let me know if you need any more help. I'll close this issue for now but feel free to re-open it.
