### ISSUE TITLE
pingdom plugin outdated

### ISSUE THREAD

**Issue by dguihal** [guardian/alerta#360]
As far as I can see/experiment the pingdom endpoint plugin doesn't match the actual API :

- Plugin waits for OPTION/GET or Pingdom now sends POST requests
- Awaited Payload data format doesn't seem to match current data format

For pingdom webhook spec, you can look at https://www.pingdom.com/resources/webhooks

Maybe this plugin could be moved to alerta-contrib to make contribs easier ?

**Comment by satterly** [comment]
Thanks for that. I'll take a look. Not possible to move webhooks to alerta-contrib without a lot of work, but interesting idea.

**Comment by satterly** [comment]
The updated pingdom webhook is available now as Alerta server version 4.9.5.
