### ISSUE TITLE
Unable to login using Google OAuth

### ISSUE THREAD

**Issue by arielbend** [guardian/alerta#376]
Hi,

I'm new to Alerta, now trying to set it up for the first time, so I definitely may be doing something wrong.

This is my setup (using Docker locally):
Running mongo-db:
docker run --name alerta-db -d mongo

Running Alerta 4.10.0:
docker run --name alerta-web --link alerta-db:db -d -p 8080:80 --env-file=envfile

Envfile:
DEBUG=True
SECRET_KEY=<secret_key>
AUTH_REQUIRED=True
ADMIN_USERS=<my_email>
ADMIN_KEY=<admin_key>
OAUTH2_CLIENT_ID=<oauth2_client_id>
OAUTH2_CLIENT_SECRET=<oauth2_client_secret>
ALLOWED_EMAIL_DOMAINS=<allowed_domain>
PROVIDER=google
MAIL_FROM=<my_email>
SMTP_PASSWORD=<my_password>
EMAIL_VERIFICATION=True
CLIENT_ID=<oauth2_client_id>
CLIENT_SECRET=<oauth2_client_secret>
MONGO_URI=mongodb://db:27017/monitoring

This is how my Google OAuth 2 client is setup (new to OAuth as well so might be issue here as well):

![image](https://user-images.githubusercontent.com/17960367/29002182-80dddcca-7aa5-11e7-8505-de82a10dd11b.png)

This is what happens when I press the login:

![image](https://user-images.githubusercontent.com/17960367/29002214-1d2e6d2e-7aa6-11e7-9fc1-e03b1dd4b53b.png)

Please let me know if you need any additional configurations / logs.
Would greatly appreciate your help.

**Comment by satterly** [comment]
It works for me. These are the steps ...

**Step 1. Create Google OAuth2 Web Client Credentials**

<img width="897" alt="screen shot 2017-08-06 at 13 16 49" src="https://user-images.githubusercontent.com/615057/29003192-f5595774-7aa9-11e7-8577-4a4bd94d7b56.png">

**Step 2. Create `envfile` with Launch environment variables**

```
$ cat envfile
DEBUG=True
SECRET_KEY=secret
AUTH_REQUIRED=True
ADMIN_USERS=nfsatterly@gmail.com
ADMIN_KEY=demo-key
OAUTH2_CLIENT_ID=379647311730-34doh3ah6qehl602nlud06m1enp3v09s.apps.googleusercontent.com
OAUTH2_CLIENT_SECRET=**redacted**
ALLOWED_EMAIL_DOMAINS=gmail.com
PROVIDER=google
MAIL_FROM=nfsatterly@gmail.com
SMTP_PASSWORD=**redacted**
EMAIL_VERIFICATION=True
MONGO_URI=mongodb://db:27017/monitoring
CLIENT_ID=379647311730-34doh3ah6qehl602nlud06m1enp3v09s.apps.googleusercontent.com
CLIENT_SECRET=**redacted**
```
(Notes: not sure why OAuth2 client ID and secret need to be defined twice. That is a bug. And "email verification" is only used for Basic Auth, not Google OAuth, so can be removed.

**Step 3. Run MongoDB**
```
$ docker run --name alerta-db -d mongo
```
**Step 4. Run Alerta**
```
$ docker run --name alerta-web --link alerta-db:db -d -p 9001:80 --env-file=envfile alerta/alerta-web
```

**Comment by satterly** [comment]
Open up the browser JavaScript console and check for any errors.

**Comment by arielbend** [comment]
Thanks for the response.

Here is what I get (after I click on the email account):

![image](https://user-images.githubusercontent.com/17960367/29006812-dd6d4aa2-7aff-11e7-9bd0-c859b7a62eb0.png)

![image](https://user-images.githubusercontent.com/17960367/29006850-7e5a4a50-7b00-11e7-9416-9dd8e1eb521e.png)


Any suggestions?

Thanks!

**Comment by satterly** [comment]
Is "Google+ API" enabled in the Google Developer console?

<img width="1042" alt="screen shot 2017-08-06 at 21 49 24" src="https://user-images.githubusercontent.com/615057/29006944-75410aa8-7af1-11e7-8b8c-fef4703114f3.png">

<img width="1080" alt="screen shot 2017-08-06 at 21 51 12" src="https://user-images.githubusercontent.com/615057/29006948-7900930c-7af1-11e7-8b8e-3655699c8321.png">

**Comment by satterly** [comment]
If I disable "Google+ API" I get the same errors as you ...

<img width="1223" alt="screen shot 2017-08-06 at 21 56 09" src="https://user-images.githubusercontent.com/615057/29006980-23f3b186-7af2-11e7-8a2b-6f0274eb1ce0.png">

**Comment by arielbend** [comment]
Bingo!
Thanks so much for your super quick help.
Can't wait to get this to our production already.
Be sure I'll be back for more help in the near future :)

**Comment by satterly** [comment]
You're welcome. 😃
