### ISSUE TITLE
Blackout improvements

### ISSUE THREAD

**Issue by m4ce** [guardian/alerta#385]
I have been using the blackout functionality and it's been working really well.

I would like to get a discussion started around the following items:

* would it be possible to support regex when matching things like resources/tags/events etc?

* any reason why one cannot create a blackout period for a given environment unless there's at least one outstanding alert currently open for that environment?

* it would be super useful if one could see the alerts popping up on the dashboard even during a blackout period rather than rejecting them straight-away. I think Alerta should still receive alerts but disable any notification for them?

**Comment by satterly** [comment]
> would it be possible to support regex when matching things like resources/tags/events etc?

Almost certainly no. The way it works at the moment is that incoming alerts are checked against the blackouts table for any matching "rules". In reality, these rules are just equality matches which means it's fast. Adding support for regex based rules would fundamentally change how this worked. That is, it would be necessary to iterate through every possible rule and evaluate it against the incoming alert which I believe would be prohibitively slow.

> any reason why one cannot create a blackout period for a given environment unless there's at least one outstanding alert currently open for that environment?

There's no reason why a user shouldn't be able to input any environment they want. PR's welcome.

> it would be super useful if one could see the alerts popping up on the dashboard even during a blackout period rather than rejecting them straight-away. I think Alerta should still receive alerts but disable any notification for them?

Blackout handling could be factored out into a plugin then it would be easy to completely disable or reconfigure completely based on your own use case. I'll look at adding this to the next release.

**Comment by m4ce** [comment]
@satterly, thanks for your comments. I will take a look at the second action point and let you know.

**Comment by m4ce** [comment]
hey @satterly, do you think you'll be able to turn the blackout plugin into the next release then? Out of curiosity, how far are you from cutting out the new release?

**Comment by satterly** [comment]
Hi @m4ce , yes, it's in the [next release](https://github.com/guardian/alerta/blob/master/alerta/plugins/blackout.py). I'm very close to a release candidate for version 5. I'm doing regression testing of the most common deployment options at the moment so any help there would be appreciated. It's meant to be API compliant with version 4 but there are a few important differences. eg. wsgi and plugin imports have changed. If you have time to deploy master branch to your (test?) environment, test it and give me feedback that would be great.

**Comment by satterly** [comment]
RC1 for Alerta Release 5 is now available for download and testing. Blackout is now a plugin. https://pypi.python.org/pypi/alerta-server/5.0.0rc1

**Comment by m4ce** [comment]
@satterly, thanks. I will do some testing.

**Comment by mirceaulinic** [comment]
Hello! Before I start reinventing the wheel, are you aware of an open-sourced blackout plugin supporting globbing or regex on resources / tags / events? Happy to start implementing one otherwise, of course, just wanted to make sure I'm not duplicating efforts. Thanks!

**Comment by satterly** [comment]
@mirceaulinic No, I'm not aware of one. If you want regex matching on alert attributes the recommended approach would be to do your regex in a plugin and if it matches then tag the alert with something like "regex-blackout" or whatever and have a standing blackout rule in Alerta that matches on any alert with tag "regex-blackout". But perhaps you have a better idea.

**Comment by mirceaulinic** [comment]
That's great, thanks @satterly!

I've looked through some of the implemented plugins, but I haven't seen a way to be able to pull the existing blackouts and match the alert attributes against the regex the user adds via the UI. Or did you mean by "recommended approach would be to do your regex in a plugin" to have the regex hardcoded into the plugin module? I was hoping to find a more dynamic way, but perhaps I'm missing something? Cheers!

**Comment by mirceaulinic** [comment]
Just a quick update here, after starting tinkering with a plugin:

- Managed to pull the list of configured blackouts by doing:

```python
from alertaclient.api import Client

client = Client()
blackouts = client.get_blackouts()
```

Was hoping for a more "embedded" way to gather the configuration, to avoid going via the API, but that's good enough I guess, unless there's a smarter way (please let me know).

- Processing the alert in `pre_receive`: the `alert` object doesn't have the tags added in a previous evaluation (that's normal), therefore `regex-blackout` won't be there initially to avoid re-evaluation against the regex (and blackout it straight away), so the alert is always evaluated against the blackouts.
  Leaving this aspect aside, it looks like once the alert gets the `regex-blackout` tag added, when there's a standing blackout rule for `regex-blackout`, looks like that alert will be forever blackout-ed, even when the associated regex blackout is removed.

- Processing the alert in `post_receive`: it seems like the tags appended don't make it into Alerta, doing something like `alert.tags.append('regex-blackout'`). Is this expected?
  A potential way to enforce this would probably be using the API again to force update the alert - but I kind of have mixed feelings about doing that. Or simply use `pre_receive` only and accept that the alerts are always evaluated against all the blackouts (i.e., just update the status when matches).

Let me know if there's anything I'm missing - any pointers would be greatly appreciated!

**Comment by mirceaulinic** [comment]
Hello, it's me again. Just wanted to leave here a note in case someone else bumps into this, I've published a plugin at https://github.com/mirceaulinic/alerta-blackout-regex - any feedback, ideas or PRs welcome!
