### ISSUE TITLE
Double handling of alerts

### ISSUE THREAD

**Issue by satterly** [guardian/alerta#386]
question about duplication in alert handling. I have a plugin that, on top of `if alert.repeat` also, checks if an attribute is filled out before processing the alert i.e: 
```
def post_receive(...):
    if alert.repeat and alert.attributes.get('is_duplicate') is not None:
        return
    # case where alert.repeat is true but alert's 'is_duplicate' attribute is None
    else:
        # process alert
```
When it sits behind a web server (uwsgi) running on 2 threads, the alerts have a tendency to be handled twice. This means that both threads are trying to process the alert causing duplication in output. I read briefly your conversation with Anton about passing attributes and solving using the (db.get_alert()) but the solution is applied to the use case of passing alert between plugins. In my case, everything is done within a single plug-in. Any idea what's going on here, and how to stop it from doing that? The way I deal with this now is to limit uwsgi to run on a single-thread but I'm not sure if that would help since I don't know what's causing the problem and it has come up before albeit when I was serving alerta using Flask instead of uwsgi. 

 @jercherng

**Comment by satterly** [comment]
Closing this for now as Release 5 rewrite might have fixed the underlying problem. Add to this issue if the problem reoccurs once you have upgraded. Thanks.

**Comment by jercherng** [comment]
thank you!
