### ISSUE TITLE
Allow for configurable housekeeping?

### ISSUE THREAD

**Issue by thehilll** [guardian/alerta#404]
Moving from 4 to 5 the API endpoint for housekeeping is a nice change, but would it be possible to allow for some configuration (either in config file or via the URL)?

We have some alerts that fire fairly infrequently...in particular we have user laptop backups that send an OK on success.  This generally happens once a day, so with the default housekeeping they would get deleted fairly regularly.

The issue this causes is that the next day when the backup works and an OK is sent a Slack post is triggered (whereas if they are not deleted it would just be counted as a duplicate).  In v4 we just modified the suggested housekeeping script to expire closed alerts after 25 hours, but with housekeeping now internal to Alerta that's a little more cumbersome.

We could also modify our alert flow (we could easily just skip posting to slack on the success in this case), but this seems like something worth considering.

I believe the code at issue (for Postgres) is:

```
DELETE FROM alerts
    WHERE (status IN ('closed', 'expired') AND last_receive_time < (NOW() at time zone 'utc' - INTERVAL '2 hours'))
    OR (severity='informational' AND last_receive_time < (NOW() at time zone 'utc' - INTERVAL '12 hours'))
```

We don't need infinite flexibility, using variables for the `2` and the `12` would be plenty.

Thanks.

**Comment by satterly** [comment]
Good suggestion. I'll see what I can do.
