### ISSUE TITLE
Noticing duplicate notification for closed alerts. Sometimes almost 16hrs apart

### ISSUE THREAD

**Issue by sushovan23** [guardian/alerta#416]
I have slack plugin configured. I got alert for closed & same verified in alerta UI. (this is expected behavior)

However sometimes after few hours(not fixed) I'm again getting the slack notification for closed alert. Is this a known issue?

**Comment by satterly** [comment]
If the alert has been deleted by a "house keeping" job because it was closed for more than 2 hours or otherwise deleted, then a subsequent "normal" alert will not be de-duplicated because it will appear to be a new alert. This would trigger a resend of the "normal" notification to Slack. Does that sound like what is happening?

**Comment by sushovan23** [comment]
Here is the flow I noticed for couple of alerts:
Major Alert was received for process crossing threshold by alerta. Plugins got executed and sent the notification for new alert. 

When process was fixed and went under the threshold. Clear/normal  alert was received was by alerta and consequently plugin was called and I received a normal/ clear alert. When I looked up alert in alerta UI , I can see the status change in UI and alert was closed. 

That should have been the flow for that alert. But suddenly after long time (not fixed) I again received the same notification for alert being in normal state- when it was already in normal state. 
Can you let me know which logs to check other than alerta.log or any configuration change which would help me check what may be causing this behavior.

**Comment by satterly** [comment]
Please check to see if a "normal" alert is received that could have triggered the duplicate notification to appear in Slack.

**Comment by sushovan23** [comment]
Thanks for the response. I was able to check the application logs & figured out that a restart in app had indeed sent normal alert. No issue with alerta or plugins.
