### ISSUE TITLE
Integration with Opsweekly

### ISSUE THREAD

**Issue by jeanfrancis** [guardian/alerta#75]
can we integrate with Opsweekly https://github.com/etsy/opsweekly for alert reporting

**Comment by satterly** [comment]
I don't understand how this would integrate with alerta as there is limited documentation. Can you explain how alerts are ingested by Opsweekly?

**Comment by jeanfrancis** [comment]
Opsweekly would get data from Alerta to generate stats about alert sent to team members

**Comment by satterly** [comment]
Looks like an [on call provider](https://github.com/etsy/opsweekly/blob/master/providers/oncall/README.md) would need to be written for alerta that queries the alerta API for alerts that occurred during the requested interval (eg. the last week on call) and returns the list of alerts in the appropriate format. Shouldn't be too hard except that my PHP is terrible.
