### ISSUE TITLE
Basic auth instead of OAuth

### ISSUE THREAD

**Issue by menardorama** [guardian/alerta#85]
Hi,

Alerta seems to be a great tool and exactly what I'm looking for (Aggregate Zabbix and PingDom)

But we don't want to use external OAuth service and don't want to implement it internally just for alerta.

Is it possible to just have a basic user/password auth ?

As this service won't be exposed on the internet I have no need to couple it to an Exernal Auth mechanism.

Thanks

**Comment by menardorama** [comment]
Or at least provide a custom oauth to get it work on a in-house oauth platform

**Comment by satterly** [comment]
Alerta does not currently support basic auth or a custom oauth platform. However, the client-side auth library is satellizer[1] and it does support either of those options so the building blocks are there.

[1] https://github.com/sahat/satellizer

**Comment by satterly** [comment]
Fixed by #87

**Comment by menardorama** [comment]
That's great thanks

**Comment by menardorama** [comment]
I tried to build it but I'm not sure which alertad.conf setup I have to do.

I kept AUTH_REQUIRED = True but I don't know how to manage that.

Do I have to set a specific parameter ? ALLOWED_EMAIL_DOMAINS for example ?

Thanks

**Comment by satterly** [comment]
Get alerta version 4.3.0 and the latest version of the web UI. You only need to set `AUTH_REQUIRED = True` in `alertad.conf` and check web UI `config.js` has `provider` set to `basic`. All other settings are fine by default.
