### ISSUE TITLE
alerta complaining about the amqp transport

### ISSUE THREAD

**Issue by satterly** [guardian/alerta#90]
2015-06-10 13:23:30,805 - alerta.app[14679]: ERROR - Failed to connect to AMQP transport mongodb://localhost:27017/kombu: Unknown option auto_start_request
2015-06-10 13:23:30,805 - alerta.app[14679]: ERROR - Server plug-in 'amqp' could not be loaded:

**Comment by satterly** [comment]
This is a problem with Kombu. It is being tracked by https://github.com/celery/kombu/issues/465 and will be fixed when https://github.com/celery/kombu/commit/8e6aed9fcf978b6c34108c0d37b720bd125f0352 is deployed.

**Comment by tdi** [comment]
Is there any workaround besides using rabbitmq?

**Comment by satterly** [comment]
The `amqp` plugin uses `kombu` as the driver precisely so that you can swap the backend for whatever you like (as long as it's supported by kombu, of course). And if you look closely at the `setttings.py` (https://github.com/guardian/alerta/blob/master/alerta/settings.py#L44) you'll actually see that by default `alertad` doesn't use RabbitMQ it uses MongoDB as the AMQP transport.

If you want to use AMQP plugin I suggest you switch to RabbitMQ or Redis but you'll need to install these as additional components.

Note that you only need to enable the `amqp` plugin if you are making use of the email or pagerduty integrations available [here](https://github.com/alerta/alerta-contrib/tree/master/integrations/amqp) or have written an AMQP integration of your own. However, if you were integrating pagerduty I would suggest using the [pagerduty plugin](https://github.com/alerta/alerta-contrib/tree/master/plugins/pagerduty) as it's easier to implement.

The AMQP integrations used to be the main was of integrating third-party apps however plugins are now the preferred method so I think I will remove the `amqp` plugin from the list of default plugins from now on.

**Comment by satterly** [comment]
AMQP plugin no longer enabled by default following #92.

**Comment by satterly** [comment]
Kombu version 3.0.26 exhibited the problem, after upgrading to Kombu version 3.0.30 it seems to be fixed.
