### ISSUE TITLE
Required config undocumented

### ISSUE THREAD

**Issue by tdi** [guardian/alerta#97]
It is undocumented that in order to properly use alerta web, one needs to add its base uri to alerta server's settings. It is needed even when the URI is the same. 

```

CORS_ORIGINS = [ 
   'http://YOUR_ALERTA_WEB_ADDRESS'
]
```

**Comment by satterly** [comment]
This is already documented on the "docs" website in the [Authentication / Cross-Origin](http://docs.alerta.io/en/latest/authentication.html#cross-origin) section.

> Cross-Origin
> If the Alerta API is not being served from the same domain as the Alerta Web UI then the
> CORS_ORIGINS setting needs to be updated to prevent modern browsers from blocking
> the cross-origin requests.

```
CORS_ORIGINS = [
    'http://try.alerta.io',
    'http://explorer.alerta.io',
    'chrome-extension://jplkjnjaegjgacpfafdopnpnhmobhlaf',
    'http://localhost'
]
```

That you couldn't find this documentation *is* a bug. Would adding a link to the docs website in the header comments of the `settings.py` configuration file have helped?

**Comment by tdi** [comment]
The problem was  that I served both Alerta API and Web UI  from the same domain, different ports though. I thinks that was of some other origin. 

>That you couldn't find this documentation is a bug. Would adding a link to the docs website in    the       header comments of the settings.py configuration file have helped?

@satterly  yes that would help
